### ISSUE TITLE
graphql-inspector-github fails to run due to "Cannot read property 'setFailed' of undefined"

### ISSUE THREAD

**Issue by adam-h** [kamilkisiela/graphql-inspector#1056]
When running `graphql-inspector-github` on v1.27.0 I get the following error:

```
> ./node_modules/.bin/graphql-inspector-github
(node:39191) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setFailed' of undefined
    at /home/adam/git/frontend/node_modules/@graphql-inspector/actions/dist/index.js:7:20
```

From poking around in `dist/index.js` changing:

    core_1.default.setFailed(e.message || e);

to

    core_1.setFailed(e.message || e);

Makes it move forward, a similar change in `run.js` gets me further. It seems like something is broken in the TS -> JS build around the default import.

Reverting to 1.25.0 works for me. I tried both Node 12 and Node 13, locally and in GitHub actions.

**Comment by kamilkisiela** [comment]
#1372 Should fix it

**Comment by kamilkisiela** [comment]
[v1.30.1](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.30.1)

**Comment by kamilkisiela** [comment]
Let me know if it's still an issue

**Comment by amandapouget** [comment]
Couldn't be more specific than "the answer is in this 25k line PR".

LOL.
