### ISSUE TITLE
Server Schema Directive Support

### ISSUE THREAD

**Issue by chalichb** [kamilkisiela/graphql-inspector#1075]
We are getting ready to implement our graph solution using AWS AppSync and Amplify. These have a set of directives which are specific to these services. 

When I'm attempting to add some sanity to our build/deploy process the following error is produced.

**error Unknown directive "aws_subscribe".**

Adding the directive definition for @aws_subscribe to the schema, the diff worked as expected. However with the definition added to the schema becomes an invalid when deployed to AWS AppSync.

The error seems to be thrown by the loadSchema function from the graphql-toolkit in the diff() in diff.ts. 

So the question is how can I introduce the directive definition before reading and parsing the schema given that it can be loaded in a variety of different way. I'm using a github ref and a local graphql file.

Specifically ... i'm looking to be able to use the following directives per AWS.

AppSync 
- directive @aws_subscribe(mutations: [String!]) on FIELD

Amplify
-       directive @model(queries: ModelQueryMap, mutations: ModelMutationMap, subscriptions: ModelSubscriptionMap) on OBJECT
-       directive @key(fields: [String!]!, name: String, queryField: String) on OBJECT
-       directive @auth(rules: [AuthRule!]!) on OBJECT, FIELD_DEFINITION
-       directive @function(name: String!, region: String) on FIELD_DEFINITION
-       directive @connection(keyName: String, fields: [String!]) on FIELD_DEFINITION
-       directive @versioned(versionField: String = "version", versionInput: String = "expectedVersion") on OBJECT
-        @searchable(queries: SearchableQueryMap) on OBJECT
-        @predictions(actions: [PredictionsActions!]!) on FIELD_DEFINITION

**Comment by benjamin-rood** [comment]
I'm guessing this is failing because you haven't actually defined the directive anywhere, correct? You just make use of these because AppSync and Amplify support them.

**Comment by chalichb** [comment]
The problem I have is that the schema that we maintain does not have these directives defined. They are automatically added to the schema which is run in AWS AppSync. Locally ... if I concat these directives with my schema, graphql-inspector works as designed. I'm proposing a CLI arg to add these directives.

**Comment by kamilkisiela** [comment]
@chalichb @benjamin-rood 
I think we don't even need those directives to detect changes. Could you try [`2.0.0-rc.1`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v2.0.0-rc.1) ?

**Comment by csplrj** [comment]
@kamilkisiela 
I am not using AWS but I need @connection for relay as mentioned in this document
https://graphql-java-kickstart.com/tools/relay/
These directives is needed to detect changes as it changes output.

I tried 2.0.0-rc.2 but the issue still remains?
Unknown directive @connection

**Comment by kamilkisiela** [comment]
@csplrj can you share more? Like in which command that happens, do you use CLI or something else?

**Comment by csplrj** [comment]
@kamilkisiela 
I use cli
graphql-inspector diff <sourcePath> <targetPath>

**Comment by kamilkisiela** [comment]
@csplrj [`v2.0.1`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v2.0.1) should fix it
