### ISSUE TITLE
Github Action creates an extra check run

### ISSUE THREAD

**Issue by BeeeQueue** [kamilkisiela/graphql-inspector#108]
The Action check currently does not update its own status. It instead always succeeds, then creates a new check which gets all the details.

Preferably the first, existing check would fail and have annotations added to it instead of the new check being created.

![image](https://user-images.githubusercontent.com/472500/55077403-f0198980-5097-11e9-9567-dcb429d14865.png)

**Comment by kamilkisiela** [comment]
Hi :) I'm currently working on writing Github Action part of Inspector from scratch and making it just a little bit independent of `@graphql-modules/github` so they won't share the login of handling `check_run` and related.

This won't happen soon, might be a week till I get there and also fix few issues in Inspector Action.

**Comment by kamilkisiela** [comment]
@BeeeQueue actually, I did it today #111 :) I will release a new version in couple of minutes

**Comment by kamilkisiela** [comment]
Release in [`v1.15.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.15.0)

**Comment by BeeeQueue** [comment]
As far as I can see it is still creating a new check every run. If I understand actions correctly you have to find the check_run that started the script, and edit it. The action is [currently still creating a new one](https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/github-actions/src/index.ts#L98).

**Comment by kamilkisiela** [comment]
That's true but it's required to add annotations. Otherwise you see everything in logs but no informations on a schema.graphql file

**Comment by BeeeQueue** [comment]
I managed to get it working with an action of my own, I didn't seem to be able to change the check message or conclusion but the annotations definitely worked!

[Example of annotation](https://github.com/BeeeQueue/famshare/runs/88259589)
[Code that does the magic](https://github.com/BeeeQueue/famshare/blob/master/actions/build/entrypoint.ts#L107)

**Comment by kamilkisiela** [comment]
Didn't know it was possible, could you add same thing here?

**Comment by kamilkisiela** [comment]
Message or conclusion is just done here https://github.com/BeeeQueue/famshare/blob/eee06409692c0384b1a29f22e44da1e104b4eea4/actions/build/entrypoint.ts#L131

**Comment by kamilkisiela** [comment]
Yesterday I moved to `actions-toolkit` and I see you're using the same thing so I'm sure it won't be a problem to create a pull request. I will appreciate it :)

**Comment by BeeeQueue** [comment]
I'll see if I can take a look at it!
