### ISSUE TITLE
Create a UI

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-inspector#12]

**Comment by kafein** [comment]
Hi @kamilkisiela, thanks for this awesome library.
I would love to help for both UI design and coding. 
Can we talk about this? 
emrah.bilbay@gmail.com

**Comment by martyganz** [comment]
I'm also up for doing some work on the UI! ;)

**Comment by kamilkisiela** [comment]
@kafein @martyganz maybe we could schedule a meeting and talk about it? I will try to prepare a todo list of things we might want to have them and features. This UI would be awesome to have. Imagine clicking through the Schema Coverage report to see exactly where in documents a field was requested and also having errors visible on hover, wild shit :))

**Comment by martyganz** [comment]
Sure thing, works for me!

**Comment by kafein** [comment]
Sure, waiting for meeting details :)

**Comment by kadirselcuk** [comment]
Can I reach the CI v3 api here?

**Comment by kamilkisiela** [comment]
GraphQL Inspector with UI and more advanced == [GraphQL Hive](https://graphql-hive.com)
