### ISSUE TITLE
CLI quite overweighted (395 deps, 62.23mb, 17350 files)

### ISSUE THREAD

**Issue by nodkz** [kamilkisiela/graphql-inspector#1201]
Just added `@graphql-inspector/cli` and was shocked by how many dependencies it uses.

It slows down CI tasks. So maybe need to create a `@graphql-inspector/ci` or `@graphql-inspector/cli-diff` package where will not be present `apollo-server`, `express`, `graphql-tools` packages. In CI there is one task - check the difference between tho schemas very fast.

**Comment by kamilkisiela** [comment]
I'm working on more granular CLI where you have `inspector.config.js` like this:

```js
module.exports = {
  use: {
    loaders: ['json', 'url', 'graphql'],
    commands: ['diff', 'introspect', 'validate'],
  },
};
``` 

And following packages installed:
```
@graphql-inspector/ci

@graphql-inspector/json-loader
@graphql-inspector/url-loader
@graphql-inspector/graphql-loader

@graphql-inspector/diff-command
@graphql-inspector/introspect-command
@graphql-inspector/validate-command
```

Each command or loader is a package and you can decide what to use. I have it working, just need to clean up the repository a bit and do some monorepo work.

**Comment by kamilkisiela** [comment]
Done in #1372

**Comment by kamilkisiela** [comment]
[v1.30.1](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.30.1). It's not documented yet but you're smart you'll figure it out :)

**Comment by nodkz** [comment]
It's amazing! 👍
Thanks!

If your config will contain the only list of plugins & commands. Then it can be removed completely by the following pattern:

```
  // check the presence of optional dependency
  // and if it does not exist then display install message and exit
  try {
    require.resolve('@graphql-inspector/diff-command');
  } catch (e) {
    console.log(dedent`
       If you want to use `diff` command you need to install `@graphql-inspector/diff-command` package explicitly:
              npm install @graphql-inspector/diff-command
              OR
              yarn add @graphql-inspector/diff-command
   `);
    process.exit();
  }

  const cmd = require('@graphql-inspector/diff-command');
  // rest code
```

By this pattern, you firstly check that package is installed. And if it resolved successfully then require it separately. Because the package may have runtime errors we should require it outside "try catch" block which checks module existence.

**Comment by kamilkisiela** [comment]
Yeah, I thought about it and wasn't sure if I to put it but I will in v1.31.0. I will remove the config for now but I want to put there something like set of commands per project. So when you run `graphql-inspector run project-a` and it checks everything related to project-a, diffing, validation etc, that was defined in the config.

**Comment by kamilkisiela** [comment]
[v1.30.4](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.30.4)

**Comment by nodkz** [comment]
> Yeah, I thought about it and wasn't sure if I to put it but I will in v1.31.0. I will remove the config for now but I want to put there something like set of commands per project. So when you run graphql-inspector run project-a and it checks everything related to project-a, diffing, validation etc, that was defined in the config.

For such task better to use package.json scripts ;)

```
{
  "scripts": {
    "gi-check1": "graphql-inspector ...one set of options",
    "gi-check2": "graphql-inspector ...second set of options",
    "gi-checkN": "graphql-inspector ...another set of options",
  }
}
```

For now, package.json is better than `inspector.config.js`.

---

In future, `inspector.config.js` may contain additional config options & several tasks. But I think it should work like Jest config (you may provide it inside package.json under its own key, as a separate file OR as several files which can be provided via config options to CLI cmd). Anyway, it's another feature and before we need to gather practical experience with current implementation before moving further. Maybe current implementation without the config file will be enough. 😉

**Comment by nodkz** [comment]
@kamilkisiela why do you not use `require.resolve`?

https://github.com/kamilkisiela/graphql-inspector/commit/0c1542542f21ebe53f46c44ab4e30b6ed57094ef#r38395428

**Comment by kamilkisiela** [comment]
I did that in 20 seconds before leaving for holidays, you're right it's a better choice
