### ISSUE TITLE
error Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by Ambro17** [kamilkisiela/graphql-inspector#1341]
Running latest docker image
`docker run -it --rm -v $PWD:/app kamilkisiela/graphql-inspector graphql-inspector similar a.gql`
with schema
```
schema {
    query: Query
} 

type Query {
    user: User
    members: User2
}

type User {
    id: ID
    username: String!
}

type User2 {
    id: ID!
    username_: String
}
```

gives error 
`error Cannot read property 'bold' of undefined`

**Comment by kamilkisiela** [comment]
Fixed in #1372

**Comment by kamilkisiela** [comment]
Could you check [v1.30.1](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.30.1)?

**Comment by Ambro17** [comment]
Of course, tomorrow I will try it

**Comment by Ambro17** [comment]
It works, the issue can be closed
