### ISSUE TITLE
Non-breaking nullability changes mistakenly registered as breaking, when the field type isn't a built-in scalar

### ISSUE THREAD

**Issue by filipncs** [kamilkisiela/graphql-inspector#140]
Changing a non-null input field to be nullable is a non-breaking change, as all valid queries before the change will still be valid after the change. 

Similarly, changing a nullable query-field to be non-null is a non-breaking change, as all valid queries and valid responses from before the change, will still be valid after the change (*).

Currently, these cases will however always be marked as breaking-changes by graphql-inspectors diff function, when the field isn't a built-in scalar, due to using object equality checking between the types, rather than comparing the names of the types.

See https://github.com/kamilkisiela/graphql-inspector/pull/139 for a proposed change. Comparing `type.toString()` is consistent with other checks throughout the codebase.

(*) I think there are actually some awkward edge cases, where overlapping fieldnames between different types can suddenly become a problem if only one of the overlapping fields suddenly becomes non-null. This is however no more or less of a problem than for the case with built-in scalars.

**Comment by kamilkisiela** [comment]
I added two more tests, will release a new version in few minutes.

**Comment by kamilkisiela** [comment]
Released as [`v1.16.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.16.0)

**Comment by ericwooley** [comment]
Are we sure this is fixed, we have a schema where a property is switched from required to optional and it's still failing. 

![image](https://user-images.githubusercontent.com/1930227/147503363-5fea165f-787f-4997-86bd-83c8f7fc095b.png)

It seems like this is the same issue? Please correct me if i'm wrong

**Comment by arcticmatt** [comment]
Also still running into this https://github.com/kamilkisiela/graphql-inspector/issues/2107

**Comment by EDjur** [comment]
Still running into this even after #2107. I'm running version 4.0.2
