### ISSUE TITLE
Make annotations opt-out on GitHub App and Action

### ISSUE THREAD

**Issue by mikestaub** [kamilkisiela/graphql-inspector#1423]
I like having the checks, but the inline annotations make it hard to do code reviews. Can I disable them?

**Comment by kamilkisiela** [comment]
Not yet but I'm working on a new version where you can decide on what GraphQL Inspector can or cannot do.

**Comment by kamilkisiela** [comment]
@mikestaub  #1425 soon to be released

**Comment by kamilkisiela** [comment]
[`v2.0.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v2.0.0) released. Read more about [new GraphQL Inspector](https://the-guild.dev/blog/new-graphql-inspector)
