### ISSUE TITLE
diff issue with physical file

### ISSUE THREAD

**Issue by CyrilleFormont** [kamilkisiela/graphql-inspector#1452]
Hi there,

I'm getting an issue when I run a diff with one or two physical files.

I'm introspecting my graphql api:
`graphql-inspector introspect  https://api/graphql --write c:/users/user/desktop/schema.graphql`

I'm then doing a diff: 
`graphql-inspector diff  c:/users/user/schema.graphql  https://api/graphql
`

I'm getting this result:
`Unable to find any GraphQL type definitions for the following pointers: c:/users/user/schema.graphql`

I correctly set-up all the packages needed at the following address : 
https://graphql-inspector.com/docs/products/ci

Note: this issue doesn't happened when I do a diff between two URLs but also appears when I exported my schema as gql or json.

version : 1.30.4

**Comment by kamilkisiela** [comment]
@CyrilleFormont You wrote to `c:/users/user/desktop/schema.graphql` but requested `c:/users/user/schema.graphql` in diff

**Comment by kamilkisiela** [comment]
@mention me if it's still an issue
