### ISSUE TITLE
Error: Directive "@deprecated" may not be used on ARGUMENT_DEFINITION.

### ISSUE THREAD

**Issue by howardhaozhang** [kamilkisiela/graphql-inspector#1481]
**Describe the bug**
With the new version of graphql-inspector, I got the following error message. 

```
oot@2e66d5ea9ff8:/home/app-user# npx graphql-inspector similar PR-schema.graphql
Error: Directive "@deprecated" may not be used on ARGUMENT_DEFINITION.
    at assertValidSDL (/home/app-user/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/home/app-user/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeSchema (/home/app-user/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:932:97)
    at Object.mergeSchemasAsync (/home/app-user/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:923:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

**To Reproduce**
I can reproduce this issue with the following simplified schema

```graphql
"The root for all read-only operations."
type Query {
  # Upercase text input
  upcase(
    # text to uppercase
    text: String @deprecated(reason: "Not all files have preview images.")
  ): String
}
```

There is no issue with the following schema.

```graphql
"The root for all read-only operations."
type Query {
  # Upercase text input
  upcase(
    # text to uppercase
    text: String 
  ): String
}
```

**Expected behavior**
```
root@2e66d5ea9ff8:/home/app-user# npx graphql-inspector similar PR-schema.graphql
info No similar types found
```

**Environment:**

- OS: 
- `@graphql-inspector/...`: 
- `graphql`: 
- NodeJS: 

**Additional context**
I wonder if it is related to the following issue in the system. 

```
root@2e66d5ea9ff8:/home/app-user# yarn global add @graphql-inspector/cli
yarn global v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/217(node:355) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] Linking dependencies...
warning "@graphql-inspector/serve-command > @graphql-inspector/commands@1.30.4" has unmet peer dependency "@graphql-inspector/loaders@1.30.4".
warning "@graphql-inspector/serve-command > @graphql-inspector/commands@1.30.4" has unmet peer dependency "yargs@15.3.1".
warning "@graphql-inspector/serve-command > express-graphql@0.9.0" has incorrect peer dependency "graphql@^14.4.1".
warning "@graphql-inspector/url-loader > @graphql-toolkit/url-loader > graphql-tools > apollo-link > apollo-utilities@1.3.3" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
[4/4] Building fresh packages...
success Installed "@graphql-inspector/cli@1.30.4" with binaries:
      - graphql-inspector
Done in 1.37s.
```

**Comment by kamilkisiela** [comment]
@howardhaozhang I think it's related to `graphql` itself, not Inspector,

here's a reproduction: https://stackblitz.com/edit/typescript-yxqnvj?file=index.ts

**Comment by howardhaozhang** [comment]
Kamil,
Thanks for you response. Is there an easy way for me to play your staff locally? I want to try if there is an issue with graphql version 14.0.0?
Thanks,
Hao
    On Monday, May 4, 2020, 11:53:06 PM PDT, Kamil Kisiela <notifications@github.com> wrote:  
 
 


@howardhaozhang I think it's related to graphql itself, not Inspector,

here's a reproduction: https://stackblitz.com/edit/typescript-yxqnvj?file=index.ts

**Comment by howardhaozhang** [comment]
Kamil,
I just figure out it show me the result immediately when I change the graphql version. It is very cool.
Thanks,
Hao
    On Tuesday, May 5, 2020, 06:52:12 PM PDT, Hao Zhang <howardhaozhang@yahoo.com> wrote:  
 
  Kamil,
Thanks for you response. Is there an easy way for me to play your staff locally? I want to try if there is an issue with graphql version 14.0.0?
Thanks,
Hao
    On Monday, May 4, 2020, 11:53:06 PM PDT, Kamil Kisiela <notifications@github.com> wrote:  
 
 


@howardhaozhang I think it's related to graphql itself, not Inspector,

here's a reproduction: https://stackblitz.com/edit/typescript-yxqnvj?file=index.ts

**Comment by kamilkisiela** [comment]
It should work with `v2.0`
