### ISSUE TITLE
GitHub application fails to find schema

### ISSUE THREAD

**Issue by AlexMabry** [kamilkisiela/graphql-inspector#1493]
**Describe the bug**
The GitHub application often fails to run on the first attempt. If I re-run it, the problem goes away.

This is the error I get: 

> Failed to complete schema check
```
ERROR: Failed to load 'projects/<blah>/schema.graphql' 
(ref: 0000000000000000000000000000000000000000)
```

Contents of our `.github/graphql-inspector.yaml`:
```
branch: 'master'
schema: 'projects/<blah>/schema.graphql'
```

**To Reproduce**
Happens on all pull requests, regardless if the schema changed or not.

**Expected behavior**
Unless the schema is actually missing, the application should always run.

**Comment by kamilkisiela** [comment]
@AlexMabry should be fixed now, give it few minutes to be deployed :)

**Comment by AlexMabry** [comment]
Thank you!
