### ISSUE TITLE
Error using documents glob pattern via cli

### ISSUE THREAD

**Issue by wjustice** [kamilkisiela/graphql-inspector#1538]
**Describe the bug**
When running `coverage` using `@graphql-inspector/cli` the documents glob pattern errors out. I'm hoping I am just making a dumb mistake here, any help is greatly appreciated.

Command:
```
graphql-inspector coverage './src/graphql-operations/*.graphql' ./src/schema.json
```
Error:
```
TypeError: Cannot read property 'document' of undefined
```

**However**, running the command with a specific file path prints the expected coverage output:
```
graphql-inspector coverage './src/graphql-operations/AnInterestingQueryName.graphql' ./src/schema.json
```

I have also tried to write a command in `package.json` scripts (note: removed quotes around glob):
```
// ...package.json
"gql-coverage": "graphql-inspector coverage ./src/graphql-operations/*.graphql ./src/schema.json"
...
```

`npm run gql-coverage` error:

```
Error: 
      Unable to find any GraphQL type definitions for the following pointers: 
        
          - ./src/graphql-operations/AnInterestingQueryName.graphql
```

☝️  `AnInterestingQueryName.graphql` is the first file in the directory from the glob. Again, changing the `package.json` script to use the `AnInterestingQueryName.graphql` path directly prints the expected output.

**Environment:**

- OS: Mac OSX Mojave
- `@graphql-inspector/cli`: 2.0.1
- NodeJS: 12.13.0

**Additional context**

**Comment by danielrearden** [comment]
@wjustice I can't seem to reproduce this issue locally. Would you be able to create a minimal repo that shows the behavior you're seeing?

**Comment by razalyalhafiz** [comment]
I am facing a somewhat similar issue but when running `diff`.

**Command**
```
graphql-inspector diff 'git:origin/master:./src/**/*.graphql' 'src/**/*.graphql'
```

**Error**
```
Error: 
      Unable to find any GraphQL type definitions for the following pointers:
        
          - git:origin/master:./src/**/*.graphql
          
    at prepareResult (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.cjs.js:590:15)
    at loadTypedefs (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.cjs.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.loadSchema (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.cjs.js:640:21)
```

Similarly mentioned by @wjustice, I do not get the error when diffing a single file at a specific filepath. Error occurs when using the glob pattern.

Unsure if this issue is related, but would definitely appreciate any help.

**Comment by kamilkisiela** [comment]
@razalyalhafiz Hi, Git loader doesn't support loading multiple files, could you open an issue in GraphQL Tools repository? http://github.com/ardatan/graphql-tools/issues/new
