### ISSUE TITLE
Syntax Error: "Unexpected ."

### ISSUE THREAD

**Issue by saerdnaer** [kamilkisiela/graphql-inspector#1592]
I get the error `ERROR: Syntax Error: Unexpected .` without really understanding why… and what this error message wants to tell me.

* Config: https://github.com/voc/voctoweb/blob/master/.github/graphql-inspector.yaml
* Error: https://github.com/voc/voctoweb/runs/861142294

**Comment by danielrearden** [comment]
@saerdnaer It looks like the schema file you're pointing to is empty?

**Comment by kamilkisiela** [comment]
#1677 improves a bit the error message

**Comment by kamilkisiela** [comment]
#1777 now it should at least give you a clue at which point it failed and at what source of schema.
