### ISSUE TITLE
Missing options in non-global-installed CLI

### ISSUE THREAD

**Issue by teamstand-arun** [kamilkisiela/graphql-inspector#1666]
**Describe the bug**

Hi, we are looking to use graphql-inspector CLI here. I see that the CLI installed with npm/yarn with --global differs in behaviour compared to the non-global couterparts.

**To Reproduce**
CLI with --global installation runs fine with --rule option:
graphql-inspector diff 'git:origin/master:./generated-sources/schema.graphql' './generated-sources/schema.graphql' --rule ./config/custom-rule.js
success No changes detected

CLI from the ./node_modules//.bin does not support this option. So "yarn run <script>" fails with this option:
./node_modules/.bin/graphql-inspector diff 'git:origin/master:./generated-sources/schema.graphql' './generated-sources/schema.graphql' --rule ./config/custom-rule.js
**error: unknown option `--rule'**

Is this expected? We would like to not use '--global' in our CI pipeline.  Can this be fixed please?

**Expected behavior**

Regardless of the installation, graphql-inspector CLI binary should respect '--rule' option 

**Environment:**

- OS:
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS:

**Additional context**

**Comment by kamilkisiela** [comment]
There's something wrong going on here. Both should accept `--rule`.

Can you run `graphql-inspector diff` in npm script instead of `./node_modules/.bin/graphql-inspector` and are you sure those two are on same version?

**Comment by teamstand-arun** [comment]
Figured that the version of the global installed package and the local installation were different. Thanks for checking. This should be fine now. Closing

Arun.
