### ISSUE TITLE
GraphQL URL is changed on graphql-inspector introspect

### ISSUE THREAD

**Issue by teamstand-arun** [kamilkisiela/graphql-inspector#1667]
> graphql-inspector introspect "http://arun.ws:8020/graphql-public-schema"
changes the URL to 
FetchError: request to http://arun**.http**:8020/graphql-public-schema failed, reason: getaddrinfo ENOTFOUND **arun.http**

**To Reproduce**
Somehow the pattern ".ws:" is replaced to ".http:" as can be seen from the trace
FetchError: request to http://arun.http:8020/graphql-public-schema failed, reason: getaddrinfo ENOTFOUND arun.http
    at ClientRequest.<anonymous> (/tools/node-v12.18.0-linux-x64/lib/node_modules/@graphql-inspector/cli/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {

Can this be fixed please?

**Expected behavior**

**Environment:**

- OS:
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS:

**Additional context**

**Comment by teamstand-arun** [comment]
Running it from the  binary installed in node_modules works though:

./node_modules/.bin/graphql-inspector introspect "http://arun.ws:8020/graphql-public-schema"
success Saved to ....

**Comment by kamilkisiela** [comment]
> /tools/node-v12.18.0-linux-x64/lib/node_modules/@graphql-inspector/cli/node_modules/node-fetch/lib/index.js:1455:11
Seems like you're running two different graphql-inspector libraries, one global, one local.

Those two are at the same version?

**Comment by kamilkisiela** [comment]
An issue with ardatan/graphql-tools#1990 
I fixed it in ardatan/graphql-tools#1991

**Comment by kamilkisiela** [comment]
Track #1674

**Comment by kamilkisiela** [comment]
@teamstand-arun GraphQL Tools [v6.2.1](https://github.com/ardatan/graphql-tools/releases/tag/v6.2.1) is not out, please upgrade `@graphql-tools/*` dependencies (maybe even in your yarn.lock or package-lock.json file)
