### ISSUE TITLE
GitHub Application occasionally fails to load schema

### ISSUE THREAD

**Issue by Ezard** [kamilkisiela/graphql-inspector#1716]
**Describe the bug**

I have a bot set up to automatically keep my dependencies up-to-date, and the GraphQL Inspector GitHub Application runs on each of these PRs. There seems to be about a 1 in 20 chance that GraphQL Inspector will fail saying "ERROR: Failed to load 'schema.graphql'". I've never seen the issue on one of my own PRs, but then again the bot generates a huge amount more than me :)

The schema file is in the root directory of the project

The only thing being altered in these PRs is package.json and package-lock.json, so no issues should be caused there

Re-running the check causes it to pass

**To Reproduce**

Not sure how to repro since it's seemingly random, but if there's any way for me to get debug log output or something then let me know and I'll grab it

**Expected behavior**

The check should not randomly fail, and then succeed whe nre-run

**Environment:**

GitHub Application

**Comment by kamilkisiela** [comment]
@Ezard could you tell me what's the name of your repository that you see the issue (PM me if it's a secret) and when it happened. I will try to track it down in logs.

**Comment by kamilkisiela** [comment]
OK I think I see it, based on your GitHub profile. Could you check if there's a `schema.graphql` file in `renovate/xxx` branch? It works for other repositories, those with renovate so maybe there's something in your renovate config. Maybe it does not do a rebase or something.

**Comment by Ezard** [comment]
@kamilkisiela I just restored the `renovate/typeorm-0.x` branch (since the checked failed on that PR), and the schema.graphql file is there, yep
The commit hash where the check failed was `2b4c732` if that helps

Here's my Renovate config in case anything looks amiss, but I don't think it could cause issues:
```
{
  "extends": [
    "config:base",
    ":semanticCommitTypeAll(chore)"
  ],
  "ignorePresets": [":prHourlyLimit2"],
  "packageRules": [
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
  ]
}
```
