### ISSUE TITLE
AWS Appsync types support

### ISSUE THREAD

**Issue by simoneBrancati** [kamilkisiela/graphql-inspector#1728]
Is there a possibility to support AWS types that can be used with AWS Appsync?

AWS types are:

- AWSDate
- AWSTime
- AWSDateTime
- AWSTimestamp
- AWSEmail
- AWSJSON
- AWSURL
- AWSPhone
- AWSIPAddress

Current error:

 `Type "AWSJSON" not found in document.`

**Comment by damienpontifex** [comment]
I was also tracking this and was merged with #1793 but yet to be released. It took me a while to find out why the `--aws` flag wasn't available as it's mentioned in the docs like at https://graphql-inspector.com/docs/essentials/validate. I'll watch for the next release and it's availability then

**Comment by kamilkisiela** [comment]
[`v2.4.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v2.4.0)
