### ISSUE TITLE
command not found: graphql-inspector

### ISSUE THREAD

**Issue by ifndefdeadmau5** [kamilkisiela/graphql-inspector#1804]
**Describe the bug**

after installing `@graphql-inspector/introspect-command` in dev dependencies, command `graphql-inspector`doesn't work with saying it's not found. I looked for it under ./bin but there wasn't any executable binary for it
**To Reproduce**
install `@graphql-inspector/introspect-command@2.3.0`
**Expected behavior**
able to run introspect command properly

**Environment:**

- OS: Mac
- `@graphql-inspector/...`: 2.3.0
- `graphql`: 14.6.0
- NodeJS: 12.9.0

**Additional context**

**Comment by kamilkisiela** [comment]
@ifndefdeadmau5 `instrospect-command` provides `graphql-inspector introspect` command, that's true but you also need to add the `@graphql-inspector/ci` package to define `graphql-inspector` command. 

You can also use `@graphql-inspector/cli` that includes all the commands.

**Comment by leethree** [comment]
There's no mention of `@graphql-inspector/ci` in the "Continuous Integration" documentation. https://graphql-inspector.com/docs/products/ci

**Comment by Urigo** [comment]
@leethree would you be willing to create a PR for the docs to add it in the right place?
Thanks!

**Comment by leethree** [comment]
@Urigo sure. here it is: https://github.com/kamilkisiela/graphql-inspector/pull/1862

feel free to edit the wording.
