### ISSUE TITLE
Github Action #approved-breaking-change-label

### ISSUE THREAD

**Issue by tbrannam** [kamilkisiela/graphql-inspector#1813]
Is there a similar path to allow for using labels to [allow for a breaking change via Tags ](https://graphql-inspector.com/docs/products/github#approved-breaking-change-label) when using the GitHub action, similar to the Github Application?

**Comment by kamilkisiela** [comment]
Not yet :(

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-inspector/pull/1852
