### ISSUE TITLE
Github action fails with "No more than 50 items are allowed"

### ISSUE THREAD

**Issue by Betree** [kamilkisiela/graphql-inspector#1840]
**Describe the bug**
I'm working on an important [refactor PR](https://github.com/opencollective/opencollective-api/pull/5204) where many fields have been removed. The GraphQL Inspector action is [failing to report](https://github.com/opencollective/opencollective-api/pull/5204/checks?check_run_id=1909267732) errors. Here are the job logs:

```
Run kamilkisiela/graphql-inspector@master
GraphQL Inspector started
Ref: 0ece47de2bccd2d88d8d19353167edbae995289c
Commit SHA: 880ece9a366c8096ae0f695b4b72bcaec4abd62d
Creating a check named "GraphQL Inspector - Schema v1"
Check ID: 1909272515
Query master:server/graphql/schemaV1.graphql from opencollective/opencollective-api
Got both sources
Built both schemas
Start comparing schemas
Changes: 79
FailOnBreaking disabled. Forcing SUCCESS
Conclusion: success
Updating check: 1909272515
Error: Invalid request.

No more than 50 items are allowed; 79 were supplied.
Updating check: 1909272515
Error: Invalid config. Failed to add annotation
Error: Invalid config. Failed to add annotation
```

**To Reproduce**
Have a pull request with more than 50 annotations. Feel free to fork & re-use https://github.com/opencollective/opencollective-api/pull/5204.

**Expected behavior**

According to https://github.com/Krizzu/eslint-check-action/issues/1:
> **The Checks API limits the number of annotations to a maximum of 50 per API request.** To create more than 50 annotations, you have to make multiple requests to the Update a check run endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. For details about how you can view annotations on GitHub, see "About status checks".

**Comment by kamilkisiela** [comment]
@Betree #1843 :)

**Comment by kamilkisiela** [comment]
Please use `master` as a version for now, I will release v2.5.0 in two weeks from now.

**Comment by Betree** [comment]
@kamilkisiela Wow thanks for the quick fix! As a future enhancement, it's possible to add more annotations:
> To create more than 50 annotations, you have to make multiple requests to the Update a check run endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. For details about how you can view annotations on GitHub, see "About status checks".

But that definitely solves the problem on our side :+1:

**Comment by kamilkisiela** [comment]
Yeah, I'm doing it in GitHub App, it splits annotations into chunks and sends multiple requests. I will create a new issue for it.

**Comment by kamilkisiela** [comment]
#1844
