### ISSUE TITLE
Github Application: Support multiple .graphqls files with extend types

### ISSUE THREAD

**Issue by marcust** [kamilkisiela/graphql-inspector#1848]
**Is your feature request related to a problem? Please describe.**

I am living in the Java Spring Boot corner of GraphQL, a common pattern in schema first development is to split up the schema in multiple `.graphqls` files (e.g. per domain) and also heavily use `extend type`.

This does not seem to work with the Github Action and Application which requires a single file for the `schema` property. It does work on the command line of graphql-inspector, this fact is not documented anywhere though.

There is an additional problem when parsing empty types though, `type Query {}` will throw an error

**Describe the solution you'd like**

Giving a glob expression like `src/main/resources/schema/**/*.graphqls` and allow empty types for extension.

**Describe alternatives you've considered**

I am aware that I can get the schema from running instances or generate pre-commit etc. but all of that is more work. With this feature I could easily enable PR checking for breaking changes.

**Comment by kamilkisiela** [comment]
There's no API available for GitHub Application to use glob pattern on files. Code search could be an option but it's only available in github.com website, not through any API.

**Comment by heuels** [comment]
@kamilkisiela you could use [GitHub Trees](https://docs.github.com/en/rest/reference/git#get-a-tree) for that, with the `recursive` option set. It's available for GitHub Applications.
