### ISSUE TITLE
Adding a new value to enum breaks BC

### ISSUE THREAD

**Issue by ossinkine** [kamilkisiela/graphql-inspector#1898]
**Describe the bug**

First of all thanks a lot for a great tool, it's really makes my life easier.
My team faced with the following question: adding a new value to enum breaks BC or not?
At first glance, it seems that this is like adding a new field to the type, does not break backward compatibility.
But then we came to the conclusion that an enum with a new value is actually a different enum, and changing type of field is BC breaking. Let's consider an example:
```graphql
enum Name
{
    JOHN
    MICHAEL
}

type Person
{
   name: Name!
}
```
This means that client expects the `name` can be only `JOHN` or `MICHAEL`. But if we add a new name the client gets an unexpected value and falls. Actually this is equivalent to changing field type:
```graphql
enum Name
{
    JOHN
    MICHAEL
}

enum AnotherName
{
    JOHN
    MICHAEL
    BENJAMIN
}

type Person
{
   name: AnotherName!
}
```

**Expected behavior**

`graphql-inspector diff` alerts about breaking BC if a new value added to enum.

**Comment by kamilkisiela** [comment]
Thanks for reaching out ❤️  
I agree it's breaking but only in some specific scenarios and in a similar way as when adding a member to a union.

https://github.com/kamilkisiela/graphql-inspector/blob/9cbf9722134c863d7ebe58677b83930094797848/packages/core/src/diff/changes/union.ts#L20-L34

https://github.com/kamilkisiela/graphql-inspector/blob/9cbf9722134c863d7ebe58677b83930094797848/packages/core/src/diff/changes/enum.ts#L22-L35

**Comment by kamilkisiela** [comment]
If you want to make it breaking you can write your own rule https://graphql-inspector.com/docs/essentials/diff#custom-rules

**Comment by kamilkisiela** [comment]
ok, I added a new rule so you don't have to :)

https://github.com/kamilkisiela/graphql-inspector/pull/1899
