### ISSUE TITLE
Adding mutation creates a "breaking change"

### ISSUE THREAD

**Issue by Rexman17** [kamilkisiela/graphql-inspector#1901]
**Describe the bug**

- added a `Mutation` to my schema which resulted in the error "Breaking changes
Schema mutation root has changed from unknown to Mutation"

**To Reproduce**
Steps to reproduce the behavior: Can't link my PR since it's a private repo

**Expected behavior**

- Expect no errors

**Environment:**

- OS:
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS:

**Additional context**

![image](https://user-images.githubusercontent.com/37306273/114722744-0e4a9480-9d08-11eb-8636-092bc56382b2.png)

**Comment by kamilkisiela** [comment]
Couldn't reproduce it https://github.com/kamilkisiela/graphql-inspector/commit/ff7c0e5d5a239d6ed88db885c982a67d64e7d416, can you share more details?
