### ISSUE TITLE
Passing different headers in different urls/schemas

### ISSUE THREAD

**Issue by joeynimu** [kamilkisiela/graphql-inspector#1909]
Hey guys,

First and foremost, thanks for the amazing work you do in and around the graphql community. 

I recently stumbled upon and need to pass different headers in different URLs when using graphql-inspector. I currently have two schemas that I'd like to do a `diff` on, and they both require authentication. One is in a staging environment, and the other is in a production environment. But currently, you can only pass one header.

I am sure changes can be made to allow for this. Maybe the command would be something like;

```bash
$ graphql-inspector diff <old-schema-url> --header="Authorization Bearer <token>" <new-schema-url> --header="Authorization Bearer <token>"
```

Does this make sense? 

If it does, I'd also like to make a PR for this with some guidance because I don't have experience building `cli` tools. It seems like the relevant code lives [here](https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/graphql-cli/diff/src/index.ts)

**Comment by tvvignesh** [comment]
Hi @joeynimu Thanks for this. We have taken this up internally. Have [started working on a fix](https://gist.github.com/tvvignesh/19e540d0211c1a3b88f08c0f59aed54b) - Will update you when we verify the same 👍

**Comment by joeynimu** [comment]
Hi @tvvignesh 

Awesome!

**Comment by joeynimu** [comment]
Thanks for this. Is already release?

**Comment by tvvignesh** [comment]
@joeynimu Hi. Not released yet.

@kamilkisiela ^^
