### ISSUE TITLE
Using Programatic API to validate documents (along with graphQL Tools)

### ISSUE THREAD

**Issue by thawsitt** [kamilkisiela/graphql-inspector#1944]
My use-case is to use GraphQL Tools + GraphQL Inspector to:

1. Merge remote schema and client schema
2. Validate client graphQL documents against the merged schema

For step-1, I followed the GraphQL Tools guide [here](https://www.graphql-tools.com/docs/schema-merging) and it worked fine.

However, I ran into some trouble in step-2 with providing **sources** to `validate` function from '@graphql-inspector/core' package. I did not find much documentation around Programatic API usage except [this page](https://graphql-inspector.com/docs/installation). 

I couldn't use the CLI since I needed to do this in a node scripts along with other additional steps.

Just adding the solution I found in case it helps anyone in the future.

This did not work. ❌

```js
const { validate } = require('@graphql-inspector/core');
const { loadDocuments } = require('@graphql-tools/load');

const documents = await loadDocuments(documentsPath, {
    loaders: [new CodeFileLoader()],
});

const invalidDocuments = validate(
    mergedSchema,
    documents,
);
```

Error

```
Error: Must provide Source. Received: undefined
    at devAssert (node_modules/graphql/jsutils/devAssert.js:12:11)
    at new Parser (node_modules/graphql/language/parser.js:82:67)
    at Object.parse (node_modules/graphql/language/parser.js:35:16)
    at readDocument (node_modules/@graphql-inspector/core/index.cjs.js:1240:34)
    at Array.map (<anonymous>)
    at validate (node_modules/@graphql-inspector/core/index.cjs.js:1368:31)
    at validateSchema (scripts/validate-schema.js:92:34)
```

However, this worked ✅. 

I found the solution from tracing through the source code [here](https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/commands/validate/src/index.ts#L36).

```js
const { validate } = require('@graphql-inspector/core');
const { loadDocuments } = require('@graphql-tools/load');
const graphql = require('graphql');

const documents = await loadDocuments(documentsPath, {
    loaders: [new CodeFileLoader()],
});

// This step was required, but not documented.
const sources = documents.map(doc => {
    return new graphql.Source(graphql.print(doc.document), doc.location);
});

const invalidDocuments = validate(
    mergedSchema,
    sources,
);
```

Hope this helps someone in the future. 🙂 

Feel free to close the issue.

Package versions used:

```
"@graphql-inspector/core": "^2.5.0",
"@graphql-tools/code-file-loader": "^6.3.1",
"@graphql-tools/load": "^6.2.8",
```

**Comment by Urigo** [comment]
@thawsitt thank you for the update!
Would you be willing to create a PR to the docs to help others who follow the same path?
Thanks!

**Comment by thawsitt** [comment]
Sure! I'll submit a PR for docs.
