### ISSUE TITLE
2.6.x not sending headers

### ISSUE THREAD

**Issue by mgrijalva** [kamilkisiela/graphql-inspector#1964]
**Describe the bug**

Our version of graphql-inspector that we use during CI was not pinned, when it upgraded to latest (2.6.x) the custom header we set was no longer being sent in the request.

**To Reproduce**

Our server requires a special "introspection" cookie (as introspection is disabled by default):
```bash
$ ./node_modules/.bin/graphql-inspector diff http://localhost:9000/pub http://localhost:9000/pub --header "Cookie:introspection=1" --rule suppressRemovalOfDeprecatedField
error { message: 'Unauthorized' }
{ message: 'Unauthorized' }
```
We checked server logs and the custom Cookie header was not sent in the request.

**Expected behavior**

`2.5.0` sends the custom header as expected:
```bash
$ yarn add @graphql-inspector/cli@2.5.0
$ ./node_modules/.bin/graphql-inspector diff http://localhost:9000/pub http://localhost:9000/pub --header "Cookie:introspection=1" --rule suppressRemovalOfDeprecatedField
success No changes detected
```

**Environment:**

- OS: OSX
- `@graphql-inspector/cli`: 2.6.1
- `graphql`: 15.5.0
- NodeJS: v14.5.0

**Additional context**

**Comment by siawyoung** [comment]
I think the issue is here:

https://github.com/kamilkisiela/graphql-inspector/compare/v2.5.0...v2.6.1#diff-c7f995eda48a992dab753a0f8236b5cea24c1fa96176e4730706bb6ec90bd355R133-R134

```
        const oldSchemaHeaders = leftHeaders || headers;
        const newSchemaHeaders = rightHeaders || headers;
```

Empty records are not falsy.

**Comment by kamilkisiela** [comment]
[`7447e16`](https://github.com/kamilkisiela/graphql-inspector/commit/7447e163f8eed682cd38a33cc510890009748cc0) should fix it

**Comment by kamilkisiela** [comment]
[`v2.6.2`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v2.6.2)
