### ISSUE TITLE
Unable to introspect esm schema

### ISSUE THREAD

**Issue by vladshcherbin** [kamilkisiela/graphql-inspector#1985]
**Is your feature request related to a problem? Please describe.**

I have an app which uses ESM imports and has global package.json `type` set to `module`. Everything is working nice, but when trying to introspect schema file, which uses esm imports an error is thrown:

![image](https://user-images.githubusercontent.com/6711845/129704931-3b55bb85-fd86-482c-a260-be80b518acaa.png)

**Describe the solution you'd like**

Would be nice to have support for esm schema files.

**Describe alternatives you've considered**

Nope

**Additional context**

- graphql-inspector 2.6.1
- nodejs 16.

Possibly related https://github.com/kamilkisiela/graphql-inspector/issues/1961

**Comment by TuvalSimha** [comment]
Hey @vladshcherbin,
You are more than welcome to update to the last `GraphQL - Inspector CLI` version (3.4.12).

After updating, please try running `introspect` again and let me know if everything is working as expected. If you're still experiencing any issues or have any questions, don't hesitate to reach out and I'll be happy to help.
