### ISSUE TITLE
diff-command does not pass down --header properly

### ISSUE THREAD

**Issue by dominik-henning** [kamilkisiela/graphql-inspector#2002]
**Describe the bug**

Using an url to fetch the schema, when i set headers in the fashion --header 'a: b' the receiving graphql server does not receive those. I debugged for a while and found out that the lines 143 and 153 are to blame.

```        const oldSchema = await loaders.loadSchema(
          oldSchemaPointer,
          {
            oldSchemaHeaders, <--- is ignored
            token,
            method,
          },
          apolloFederation,
          aws,
        );
        const newSchema = await loaders.loadSchema(
          newSchemaPointer,
          {
            newSchemaHeaders, <--- is ignored
            token,
            method,
          },
          apolloFederation,
          aws,
        );
```

the called urlloader and the internally used module for this task ignores the mentioned options and expect in fact an option named headers instead. When i change the cjs module locally to pass headers options the command works fine.

I would have written code to fix this but i am pretty new to github and couldnt figure it out

**Comment by kamilkisiela** [comment]
released in v3.0.0
