### ISSUE TITLE
Error: Cannot convert object to primitive value in GHA

### ISSUE THREAD

**Issue by ertrzyiks** [kamilkisiela/graphql-inspector#2016]
**Describe the bug**

When I run github action on my schema it crashes with
![Screenshot 2021-09-28 at 16 50 25](https://user-images.githubusercontent.com/2437969/135114806-c94eec5d-2f7e-4371-9a0f-717109806fa7.png)

Is #1959 available to the github action?

**To Reproduce**

Have a type with default input value like
https://github.com/ertrzyiks/graphql-inspector-issue-2016

Run `kamilkisiela/graphql-inspector` github action on such schema
https://github.com/ertrzyiks/graphql-inspector-issue-2016/pull/1/checks?check_run_id=3736230467

**Expected behavior**

No runtime errors

**Comment by kamilkisiela** [comment]
Released in v3.0.1

**Comment by ertrzyiks** [comment]
@kamilkisiela thank you for the fast reaction ⚡

**Comment by ertrzyiks** [comment]
It still happens to my schema, because I have an array of object as a default value and this array is matched with this condition
https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/core/src/utils/string.ts#L82

We do array.toString() but array objects suffer from the same error.

![Screenshot 2021-10-07 at 08 27 56](https://user-images.githubusercontent.com/2437969/136331183-651a10ea-d4e0-4cc5-98f5-fb2c68e53060.png)
