### ISSUE TITLE
Removing unused scalar causes validation failure

### ISSUE THREAD

**Issue by GeoffreyEmerson** [kamilkisiela/graphql-inspector#2018]
**Describe the bug**

We have implemented graphql-inspector using `suppressRemovalOfDeprecatedField` in our build process.

Recently we stopped using a particular scalar, but I discovered that removing it from the schema caused the validator to mark it as a breaking change which halts our build process.

Unfortunately, scalars cannot be deprecated. Attempting to deprecate causes the error `GraphQLSchemaValidationError: Directive "@deprecated" may not be used on SCALAR.` on server start.

**To Reproduce**

1. Create a schema which contains an unused custom scalar, and deploy it so that it becomes the standard against which the validator runs.
2. Remove the scalar and use graphql-inspector to compare against the version that contains the scalar.

**Expected behavior**

Unused scalars should pass, since removing something that is unused is not really a breaking change.

**Environment:**

- OS: linux
- "@graphql-inspector/ci": "2.6.1"
- "@graphql-inspector/diff-command": "2.6.1"
- "@graphql-inspector/url-loader": "2.6.1"
- "graphql": "15.4.0"
- NodeJS: 14

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-inspector/commit/5ef747cc1db7affdb3979831ce6a0c3e2663c60a it will be available in next major version

**Comment by kamilkisiela** [comment]
released in v3.0.0
