### ISSUE TITLE
Latest Dockerfile not up to date with latest version of graphql-inspector

### ISSUE THREAD

**Issue by ides15** [kamilkisiela/graphql-inspector#2034]
**Describe the bug**

I'm trying to run graphql-inspector in my pipeline to find breaking changes between the schema file in my repository's `master` branch and the new schema file. I'm getting this error when running graphql-inspector as a Docker container:

```sh
/bin/sh: 1: git: not found
```

I looked into the [Dockerfile that is shown in Dockerhub](https://hub.docker.com/r/kamilkisiela/graphql-inspector/dockerfile) and it looks like it isn't up to date with [Dockerfile-cli in the repository](https://github.com/kamilkisiela/graphql-inspector/blob/master/Dockerfile-cli) - the key difference being that the Dockerfile-cli in the repository has the line to add the `git` binary.

**To Reproduce**

```sh
docker run -v $PWD:/app kamilkisiela/graphql-inspector graphql-inspector diff git:origin/master:./old.graphql new.graphql
```

**Expected behavior**

Any changes would be shown in the console (similar to when you run the command from the CLI).

**Environment:**

- OS: MacOS 10.15.7
- `@graphql-inspector/...`: latest
- `graphql`: ^15.5.0
- NodeJS: 12.16.2

**Additional context**

**Comment by kamilkisiela** [comment]
#2139
