### ISSUE TITLE
GitHub action fails large schemas when referencing a schema file from the repo

### ISSUE THREAD

**Issue by jeremygiberson** [kamilkisiela/graphql-inspector#2079]
**While attempting to use the graphql-inspector github action we ran into unexpected behavior. The job failed indicating that it had trouble parsing the schema. This was odd because the cli version of the inspector worked w/out issue.**

![check-schema-before-edited](https://user-images.githubusercontent.com/487411/154547379-fb7a7185-7fe1-4957-a251-e905cfd6b8ce.jpg)

After digging around for quite some time, I found that the `loadFile` operation uses a GraphQL query to retrieve the contents of the schema. Unfortunately there is no guarantee that the full contents of the file will be returned from the API call.

If you have a relatively large schema, the loadFile won't be successful because the query used to fetch the blob contents from GitHub's GraphQL API may be truncated.
This likely will result in an error during GitHub Action execution along the lines of:
> Error: Unexpected end of JSON input

**To Reproduce**
1. Have a sufficiently large schema. The exact limit of a blob content length that wont be truncated is not defined.
2. Query the graphql api for the blob content (text field), additionally include the field `isTruncated`. Below is the query from `packages/action/src/run.ts`, targeted at a blob from this project to demonstrate that results can be truncated:
```
query GetFile($repo: String!, $owner: String!, $expression: String!) {
      repository(name: $repo, owner: $owner) {       
        object(expression: $expression) {
          ... on Blob {
            byteSize
            isTruncated
            text
          }
        }
      }
    }
 variables {
  "repo":"graphql-inspector",
  "owner":"kamilkisiela", 
  "expression":"master:action/index.js",
}   
```
3. Observe that the blob content has been truncated
```
{
  "data": {
    "repository": {
      "object": {
        "byteSize": 706058,
        "isTruncated": true,
        "text": ".. the content will be truncated, check .length and compare w/ byteSize"
      }
    }
  }
}
```

**Expected behavior**
I expected graphql inspector to be able to load the schema and perform validations.

**Environment:**

- GitHub GraphAPI: current

**Additional context**

This issue has been remarked on in a few github community board discussions:
* https://github.community/t/github-graphql-v4-truncating-text-field-of-large-blob/14670
* https://github.community/t/fetching-truncated-files/13779

** Remediation **
It appears that it may be necessary to fall back to using GitHub's REST API to retrieve the contents of the file when the GraphQL API truncates it. 

1. Add `isTruncated` and `oid` fields to the query
2. Perform the GraphQL query. 
3a. If isTruncated is true, perform an extra call to retrieve the contents from the url: `https://api.github.com/repos/${owner}/${repo}/git/blobs/${oid}`
3b. If isTruncated is false, use the content of text field 

I was able to setup a script that retrieved the OID of the blob for the schema, and then fetched the full contents from the REST API. I'll be creating a Pull Request shortly w/ this solution.

**Comment by kodai3** [comment]
@jeremygiberson 

I'm facing same issue, did you find any workaround for this ?

**Comment by jeremygiberson** [comment]
> @jeremygiberson
> 
> I think I'm facing same issue, did you find any workaround for this ?

Yes. I opened a PR to fix it: https://github.com/kamilkisiela/graphql-inspector/pull/2080

you can update the GitHub action and point to a patch branch to fix it. 
ie this is what we use in our GitHub workflow:

- uses: formidablelabs/graphql-inspector@2079-loadfile-rest-fallback # patch of kamilkisiela/graphql-inspector

**Comment by kodai3** [comment]
@jeremygiberson 

Thank you for the quick response and the PR.

This indeed fixed the issue for me as well !!

**Comment by kamilkisiela** [comment]
Released recently
