### ISSUE TITLE
Error: was filtered because it contains an invalid GraphQL schema definition

### ISSUE THREAD

**Issue by MrDesjardins** [kamilkisiela/graphql-inspector#208]
Hello,

I have a running client that consume a GraphQL service. I can query without any issue. I am trying to use the graphql-inspector but this one keeps saying:

> was filtered because it contains an invalid GraphQL schema definition

I am using:

`./node_modules/.bin/graphql-inspector validate ./src/**/*.{ts,tsx} ./graphql/allSchema.graphql`

and the result is 

>File "./src/Shared/ContainerComponents/GraphQLExperimentation1.tsx" was filtered because it contains an invalid GraphQL schema definition!
File "./src/Shared/ContainerComponents/GraphQLExperimentation2.tsx" was filtered because it contains an invalid GraphQL schema definition!

>error All found files for glob expression "./src/**/*.tsx" are not valid or empty, please check it and try again!

It would be helpful to know what "invalid" means? Meanwhile, is there an option to get further detail because from my perspective the schema is valid. The VSCode extension (GraphQL for VSCode) uses the static file `./graphql/allSchema.graphql` and does not detect any issue. The execution of the query is also flawless.

The two .tsx files are different. The first one uses:

 ```
const result: ApolloQueryResult<Proto.Query> = await this.client.query<Proto.Query>({
 query: gql`
                    query Proto {
                        entityA(id: 1) {
                            name
                            id
                        }
                    }
                `
         });
```

The second one use:

```
<Query
    query={gql`
        query Proto2 {
            entityA(id: 1) {
                name
                id
            }
        }
    `}
>
```

Thank you in advance.

**Comment by MrDesjardins** [comment]
@kamilkisiela I see that the issue is marked as "enhancement". While having more context about what is wrong is an enhancement, I believe that there is also a bug. The GraphQL schema is valid and in production at the moment. The toolings around the schema (Playground, Voyageur, etc) are all consuming the GraphQL schema without issue as well as the Express server that host the Apollo Server and the consumer code who build the _gql_. However, the graphql-inspector fails. 

I'll get the source code of graphql-inspector and try to diagnostic the library. I'll post my finding.

**Comment by MrDesjardins** [comment]
Update: I've done some test and here is something very odd.

I moved the `gql` into a .ts file and have the .tsx files importing the gql.

This command:
```
./node_modules/.bin/graphql-inspector validate ./src/**/*.ts ./graphql/allSchema.graphql
./node_modules/.bin/graphql-inspector validate ./src/**/*.tsx ./graphql/allSchema.graphql
```
Output:

>success All documents are valid
success All documents are valid

However, this is wrong because I explicitly wrote fake/bad graphQL query into the `gql` tag.

If I change the command to:
```
./node_modules/.bin/graphql-inspector validate ./src/**/*.{ts,tsx} ./graphql/allSchema.graphql
``` 

I get:

>error All found files for glob expression "./src/**/*.tsx" are not valid or empty, please check it and try again!

On the former, I expect that it returns an issue on the .ts file. One the latter, I was expecting the same output than the first command.

**Comment by kamilkisiela** [comment]
I'll see if it's something done by `graphql-inspector` or `graphql-toolkit` (a dependency)

**Comment by MrDesjardins** [comment]
Also, concerning the former issue. Moving the GraphQL into a .graphql file instead of having it directly into a .ts or .tsx file fixed the issue.

```
./node_modules/.bin/graphql-inspector validate ./src/**/*.graphql ./graphql/allSchema.graphql
```

So, it seems that analyzing ts/tsx file causes an issue while the same query in a graphql file works as expected.

**Comment by leethree** [comment]
I think you need to wrap the parameter in quotes. like this
```
graphql-inspector validate "./src/**/*.{ts,tsx}" ./graphql/allSchema.graphql
```

**Comment by kamilkisiela** [comment]
yeah, OS turns glob into an array of files

**Comment by kamilkisiela** [comment]
@MrDesjardins we did some work libraries that GraphQL Inspector depends on, could you check if `1.22.1` works for you?
