### ISSUE TITLE
Trying to install graphql-tools using npm and getting an error - No matching version found for @graphql-tools/utils@^8.6.2.

### ISSUE THREAD

**Issue by vishnukavach** [kamilkisiela/graphql-inspector#2084]
**Describe the bug**

Trying to install graphql-inspector using npm and getting an error:

```
$npm install @graphql-inspector/cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @graphql-tools/utils@^8.6.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kvishnu/.npm/_logs/2022-02-24T16_55_08_473Z-debug.log
```

**To Reproduce**

`npm install @graphql-inspector/cli@latest`

**Expected behavior**
Expected  to install the library

**Environment:**

- OS: Mac
- NodeJS: v12.22.6

**Additional context**
graphql-tools/utils@^8.6.2  released
[https://github.com/ardatan/graphql-tools/releases/tag/%40graphql-tools%2Futils%408.6.2](url)

Able to install Previous release 

```
$npm i @graphql-tools/utils@^8.6.1 
npm WARN grpc-kit@0.2.0 requires a peer of @grpc/proto-loader@^0.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN tenant-api-gw@0.0.1 No license field.
npm WARN The package @types/express is included as both a dev and production dependency.

+ @graphql-tools/utils@8.6.1
added 1 package from 1 contributor and audited 1979 packages in 10.375s
```

**Comment by TuvalSimha** [comment]
@vishnukavach 
I was tried to reproduce it, and all working just fine. Did you still have this issue?

**Comment by vishnukavach** [comment]
yes @TuvalSimha  It is working fine now, The issue occurred long back
