### ISSUE TITLE
Implement logging to file for the CLI

### ISSUE THREAD

**Issue by LunaticMuch** [kamilkisiela/graphql-inspector#2117]
The CLI tool is great but it logs everything on the stdin only. While the stdin can be redirected to a file, the CLI should provide an argument like `--log` to dump the result into a file. This might be also taken to the extreme of providing text and html log.

I am happy to collaborate on making this, if somebody else sees a value.

- [ ] Log into text file from cli argument
- [ ] Log into html file from cli argument

**Comment by TuvalSimha** [comment]
Still relevant?
@LunaticMuch

**Comment by LunaticMuch** [comment]
Actually I don't think so.
I close it.
