### ISSUE TITLE
GitHub Action Fails with `Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by SudharakaP** [kamilkisiela/graphql-inspector#2128]
**Describe the bug**

It seems that the latest version of the `graphql-inspector` fails when comparing schemas with the error; `Cannot convert undefined or null to object`

**To Reproduce**

On our repo we use the `graphql-inspector` through the GitHub Action, and recent runs all seems to fail. Examples,

https://github.com/opencollective/opencollective-api/runs/7215036107?check_suite_focus=true

https://github.com/opencollective/opencollective-api/runs/7214924629?check_suite_focus=true

https://github.com/opencollective/opencollective-api/runs/7214917185?check_suite_focus=true

However downgrading to v3.1.2 seems to work; https://github.com/opencollective/opencollective-api/pull/7717

**Expected behavior**

Since v3.1.3 do not have any breaking changes according to the [release notes](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v3.1.3), it's expected to behave the same as v3.1.2

**Comment by kamilkisiela** [comment]
#2129
