### ISSUE TITLE
Notify about schema changes via Slack / Discord

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-inspector#214]
- [x] slack
- [x] discord
- [x] webhook

**Comment by zionts** [comment]
hmm... how about a more generic webhook implementation where people can write a webhook that handles the information and forwards it to their favorite service? Then this can be followed up by a generic webhook handler that can forward to whichever channel makes the most sense for them, translating the event information's default JSON into the format that works best for them?

**Comment by kamilkisiela** [comment]
#1425 soon to be released

**Comment by kamilkisiela** [comment]
[`v2.0.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v2.0.0) released. Read more about [new GraphQL Inspector](https://the-guild.dev/blog/new-graphql-inspector)
