### ISSUE TITLE
Unable to find any GraphQL type definitions for the following pointers

### ISSUE THREAD

**Issue by FerasAlazzeh** [kamilkisiela/graphql-inspector#2201]
Describe the bug

This is the same issue described here: https://github.com/kamilkisiela/graphql-inspector/issues/2001

which was closed however seems to still be broken on latest versions of inspector

Unable to find any GraphQL type definitions for the following pointers

The following errors out when use wildcard.

```
graphql-inspector validate ./client/**/*.graphql  ./schema.graphql
```
Although when I copy/paste all the graphql queries/mutations into document.graphql, it never errors out.

```
graphql-inspector validate ./client/documents.graphql  ./schema.graphql
```

To Reproduce

First Approach
client/queries/companies.graphql
```

query getCompanies {
  companies {
    id
  }
}

```
client/queries/hotels.graphql
```
query getHotels {
  hotels {
    id
  }
}
```
schema.graphql

```
type Company {
  id: ID!
}

type Hotel {
  id: ID!
}

type Query {
  companies: [Company]!
  hotels: [Hotel]!
}
```
output
```
➜  test_graphql graphql-inspector validate *.graphql  ./schema/schema.graphql
Error: 
      Unable to find any GraphQL type definitions for the following pointers:
        
          - hotels.graphql
          
    at prepareResult (/Users/falazzeh/.config/yarn/global/node_modules/@graphql-tools/load/index.js:561:15)
    at loadTypedefs (/Users/falazzeh/.config/yarn/global/node_modules/@graphql-tools/load/index.js:527:12)
    at async Object.loadSchema (/Users/falazzeh/.config/yarn/global/node_modules/@graphql-tools/load/index.js:612:21)
```

Environment:
OS: MacOS Monterey
@graphql-inspector/...: 3.4.0

**Comment by FerasAlazzeh** [comment]
It seems to work if I do the following 

`graphql-inspector validate ./client/**/*.graphql  ./schema.graphql`

rather than 

`graphql-inspector validate *.graphql  ./schema/schema.graphql`

If this is intended we should include that in the docs :)

**Comment by TuvalSimha** [comment]
Hey @FerasAlazzeh,
Thank you for the bug report! 

I was trying to reproduce your issue and I have a solution for you.
When you did this -> `graphql-inspector validate ./client/**/*.graphql  ./schema.graphql` it might result be -> `graphql-inspector validate ./client/foo/1.graphql ./client/foo/2.graphql ./client/bar/1.graphql  ./schema.graphql`.

 So, try to add `"` before the path of the documents. Like that:
`graphql-inspector validate "./client/**/*.graphql" ./schema.graphql` ,and like we did in our docs example here: https://the-guild.dev/graphql/inspector/docs/essentials/validate
