### ISSUE TITLE
Client schema directives support

### ISSUE THREAD

**Issue by alx13** [kamilkisiela/graphql-inspector#228]
Hi,
When validating schema I'm getting errors about [`@connection`](https://www.apollographql.com/docs/react/features/pagination#connection-directive) directive:
```
- Unknown directive connection.
```
Is there a way to allow usage of custom directives in documents?

**Comment by kamilkisiela** [comment]
As a workaround you could define that directive in your schema. In long term we could include those directives under `--apollo` or `--relay` flags or as a built-in thing

**Comment by kamilkisiela** [comment]
If you want to implement it, I could help you :)

**Comment by imranolas** [comment]
It would useful to support the broader case of custom directives in general. In addition to apollo connections it's also quite commonplace to add directives to handle auth.

**Comment by steebchen** [comment]
Also there is @client for local state management

**Comment by kamilkisiela** [comment]
#505 should add Apollo specific directives. In order to use custom directives, you can just include their definitions in the GraphQL Schema.
