### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by MrDesjardins** [kamilkisiela/graphql-inspector#233]
Hello,

I tried to build the solution on my local machine (MacBook Pro) and could not. I suppose, I am missing a build step but I cannot find out any documentation in the readme.md to guide me.

**Steps:**
1- Get the code with git clone https://github.com/kamilkisiela/graphql-inspector.git graphqlinspector
2- yarn install
3- yarn build

I am getting many `ERR! yarn run build`

![image](https://user-images.githubusercontent.com/1014796/56515845-c6fce500-64ed-11e9-9922-90080bcbe5da.png)

I also tried to run `yarn run build:github` without better success. This time getting over 60 TypeScript errors.

Finally, I find out a `Dockerfile`, I tried `docker build .` It ran without issue but there is no container running, neither file compiled.

It would help people to have some instructions on how to build the project.

**Comment by MrDesjardins** [comment]
Update:
Going one by one in all `packages` and performing `yarn install` and `yarn build` works. All commands are successful. 

However, I do not see any folder `dist` even if the `.tsconfig` mention the `outDir` to be `./dist`. I also found intriguing that the `cli` project requires the `ui` project to be built. It might be a misunderstanding but is a React application hence not clear why needed. Nonetheless,  at the moment, the piece that is puzzling is where are the compiled files.

**Comment by kamilkisiela** [comment]
I don't know how it might not work for you since it works for CI and Github Actions.

What I did and what CI does:

> git clone git@github.com:kamilkisiela/graphql-inspector.git`
> yarn
> yarn build

Could you try again?
