### ISSUE TITLE
Rename coverage.stats.numFiledsCovered to coverage.stats.numFieldsCovered

### ISSUE THREAD

**Issue by jirikuncar** [kamilkisiela/graphql-inspector#2424]
Strategy:

1. Add new field `numFieldsCovered` in a minor version.
2. Announce deprecation of `numFiledsCovered`.
3. Remove `numFiledsCovered` in future major version.

**Comment by TuvalSimha** [comment]
Hey @jirikuncar,
Oops! missing this typo, thank you!
Your pull request was reviewed. #2425
