### ISSUE TITLE
`command not found` error with cli version 3.4.10 

### ISSUE THREAD

**Issue by davidalbers** [kamilkisiela/graphql-inspector#2430]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

After updating to the latest version, 3.4.10, I'm getting a `command not found` error.

**To Reproduce** Steps to reproduce the behavior:

```
$ npm install -g graphql @graphql-inspector/cli
$ graphql-inspector --help
zsh: command not found: graphql-inspector
```

**I don't see the error on 3.4.9.**

**Expected behavior**
No error

**Environment:**

- OS: macOS 13.2.1
- `@graphql-inspector/...`: @graphql-inspector/cli: 3.4.10
- `graphql`:
- NodeJS: 16.14.0

**Additional context**

**Comment by epmatsw** [comment]
Looks like the `bin` entry got dropped by https://github.com/kamilkisiela/graphql-inspector/commit/34f84e8f58a083f56d2d049a3b865d4fdfa468bc#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L16-L18 in https://github.com/kamilkisiela/graphql-inspector/pull/2419

**Comment by TuvalSimha** [comment]
Hey @epmatsw  and @davidalbers,
Thank you for this new issue, we just released a new version with the `bin`, this should fix the `command not found` issue.
