### ISSUE TITLE
3.4.11 CLI throws syntax errors

### ISSUE THREAD

**Issue by strmer15** [kamilkisiela/graphql-inspector#2432]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

If I install and run the CLI to get the help output (or any other command), I get a bunch of errors about the syntax of the script not being correct. It appears that the script should have a hashbang line like `#!/usr/bin/env node` to tell the current shell to run it using Node, otherwise it interprets it as a shell script.

**To Reproduce** Steps to reproduce the behavior:

```
cplummer:~/work/api (master)$ npm install --global @graphql-inspector/cli

added 221 packages in 14s

21 packages are looking for funding
  run `npm fund` for details
cplummer:~/work/api (master)$ 
cplummer:~/work/api (master)$ 
cplummer:~/work/api (master)$ graphql-inspector --help
/home/cplummer/.nvm/versions/node/v18.15.0/bin/graphql-inspector: line 1: use strict: command not found
/home/cplummer/.nvm/versions/node/v18.15.0/bin/graphql-inspector: line 2: syntax error near unexpected token `exports,'
/home/cplummer/.nvm/versions/node/v18.15.0/bin/graphql-inspector: line 2: `Object.defineProperty(exports, "__esModule", { value: true });'

```

**Expected behavior**

I shouldn't get any errors.

**Environment:**

- OS: Ubuntu 22.04
- `@graphql-inspector/cli`: 3.4.11
- `graphql`: 15.8.0
- NodeJS: 18.15.0

**Additional context**

**Comment by vindard** [comment]
Bump, this broke our github actions as well

```
Checking compatibility with current main branch of galoy-mobile
npm WARN exec The following package was not found and will be installed: @graphql-inspector/cli@3.4.11
/home/runner/.npm/_npx/439a8de4a40b90f8/node_modules/.bin/graphql-inspector: 1: use strict: not found
/home/runner/.npm/_npx/439a8de4a40b90f8/node_modules/.bin/graphql-inspector: 2: Syntax error: word unexpected (expecting ")")
Checking compatibility with v2.1.66-618795af
/home/runner/.npm/_npx/439a8de4a40b90f8/node_modules/.bin/graphql-inspector: 1: use strict: not found
/home/runner/.npm/_npx/439a8de4a40b90f8/node_modules/.bin/graphql-inspector: 2: Syntax error: word unexpected (expecting ")")
Checking compatibility with v2.1.79-d327c74
/home/runner/.npm/_npx/439a8de4a40b90f8/node_modules/.bin/graphql-inspector: 1: use strict: not found
/home/runner/.npm/_npx/439a8de4a40b90f8/node_modules/.bin/graphql-inspector: 2: Syntax error: word unexpected (expecting ")")
```
