### ISSUE TITLE
Enable globbing with github actions

### ISSUE THREAD

**Issue by steebchen** [kamilkisiela/graphql-inspector#250]
Just like with the CLI, I would like to use glob patterns in the .github/graphql-inspector.yml config:

```
  path: "**/*.graphql"
```

However, this currently results in

```
✖  fatal     Error: Failed to load '**/*.graphql' (ref: master) 
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:210:35
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:44:23)
    at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:25:53)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

because it probably looks for a single file.

**Comment by kamilkisiela** [comment]
It might be hard to implement or even impossible because we use Github's API to fetch files and it doesn't support glob patterns. Maybe there's a way to workaround and something like search results + file fetching would work.

**Comment by steebchen** [comment]
Interesting, didn't know that. The problem is that I split my schema files into multiple paths to keep it organized, and even when I would use graphql-inspectors's CLI to generate a single schema, graphql-inspector-github should annotate the original file but probably couldn't even annotate the generated file.

**Comment by kamilkisiela** [comment]
The thing is, GraphQL Inspector App or Action doesn't understand how to annotate schema when there are multiple .graphql files. That's why it requires a single `.graphql`.

As a workaround you can do:

	$ graphql-inspector introspect path/to/files/*.graphql --write schema.graphql

This will merge .graphql files turn that into Schema and print the output.

**Comment by steebchen** [comment]
I understand, I will just stick with the normal CLI in my CI The Github Action does not provide any more functionality if you don't have anything in a single schema file which I doubt is the normal case even for small apps. Don't get me wrong though, I am really thankful for having graphql-inspector in my CI (also for queries for the client-side).

**Comment by kamilkisiela** [comment]
We use it as part of git hook in pretty much all of our client's apps, some reaches millions of people per month with huge codebase and GraphQL Schema.

Git hook runs `$ graphql-inspector introspect` or sometimes `$ graphql-codegen --config codegen-introspect.yml` and developers are happy. They see what has changed because it's in one file (bitbucket) and they get annotations (github).

**Comment by steebchen** [comment]
So you use one single schema file for the whole API and commit it to git?

**Comment by kamilkisiela** [comment]
We have Schema defined in multiple places, usually within .graphql or .ts files but we extract that into a single file with git hook. Just for GraphQL Inspector and some codegen things.

**Comment by steebchen** [comment]
Okay, and I assume that file is committed into git so that graphql-inspect-github can annotate the code inline, right? Otherwise, I don't see a reason to commit a full schema.graphql(s) because codegen handles globs fine (at least for the client, I'm using a different codegen lib for the GraphQL server).

**Comment by kamilkisiela** [comment]
Yes + we get Intellisense in IDEs thanks to that

**Comment by steebchen** [comment]
Got it, thanks. Actually we get that too without generating the extra schema.graphqls, we use IntelliJ with the GraphQL extension and you can just specify globs for your schema files such as `api/**/*.graphqls` in the .graphqlconfig. Works perfectly for type checking, highlighting, "go to definition", "show usages", etc.
