### ISSUE TITLE
CLI custom headers

### ISSUE THREAD

**Issue by gimoteco** [kamilkisiela/graphql-inspector#258]
Hi, I tried to use graphql-inspector cli to validate two authenticated graphql servers. My servers are using authentication via bearer token and I didn`t find anyway I can pass custom headers to my requests (just found --token option that only works for github). Would be awesome have this feature. Thanks

**Comment by kamilkisiela** [comment]
#281 should do it :)

**Comment by gimoteco** [comment]
Thanks

**Comment by kamilkisiela** [comment]
released as `1.20.`
