### ISSUE TITLE
Diff does not identify changes in schema directives

### ISSUE THREAD

**Issue by gmac** [kamilkisiela/graphql-inspector#2618]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Diffing a schema does not identify changes in schema directives, which can still be an important change. For example:

```graphql
type Alpha {
  id: ID!
  title: String
}
```

The above should register a change when the following transformation appears:

```graphql
type Alpha {
  id: ID!
  title: String @external
}
```

**Comment by TuvalSimha** [comment]
Hey @gmac,
Totally agree, we need to support this. I will try to work on it soon.
Thank you!
