### ISSUE TITLE
Security issue because of @babel/core package

### ISSUE THREAD

**Issue by BabakScript** [kamilkisiela/graphql-inspector#2658]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
There is a security issue reported for one of the dependencies "@babel/core":
<img width="805" alt="image" src="https://github.com/kamilkisiela/graphql-inspector/assets/85823065/20d0a794-146c-4d91-80bd-87f94aaccaf7">

**To Reproduce** Steps to reproduce the behavior:
Just run this command to see the issue:
```
pnpm audit
```

**Expected behavior**

**Environment:**

- OS:
- `@graphql-inspector/cli`: 4.0.2
- `graphql`:
- NodeJS:

**Additional context**

**Comment by TuvalSimha** [comment]
Hey @BabakScript  :)

Sounds great! You are more than welcome to work on it

**Comment by TuvalSimha** [comment]
https://github.com/kamilkisiela/graphql-inspector/pull/2719/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6
