### ISSUE TITLE
Documentation missing for `--ignore` in the `validate` command

### ISSUE THREAD

**Issue by strmer15** [kamilkisiela/graphql-inspector#2693]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [x] 4. A pull request is pending review

---

**Describe the bug**

The documentation for the `validate` command is missing the `--ignore` option as part of the Flags.

**To Reproduce** Steps to reproduce the behavior:

Go to [the documentation site for `validate`](https://the-guild.dev/graphql/inspector/docs/commands/validate#flags) and note that the `--ignore` option is not documented.

**Expected behavior**

[The site](https://the-guild.dev/graphql/inspector/docs/commands/validate#flags) should show the `--ignore` option with a description of what it does.

**Environment:**

N/A

**Additional context**

The `--ignore` option is defined at https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/commands/validate/src/index.ts#L231

It was added in https://github.com/kamilkisiela/graphql-inspector/commit/bcf4acd9a2c8bc50a487f340921b510fcdddbbcf

**Comment by TuvalSimha** [comment]
@strmer15  thank you!
