### ISSUE TITLE
Option to let `diff` ignore deprecated fields

### ISSUE THREAD

**Issue by riffraff** [kamilkisiela/graphql-inspector#287]
I sometimes want to drop deprecated fields which are no longer in use. 

I'd like to have a switch for ignoring removals on deprecated fields, so that i.e. removing a non-deprecated field is considered a breaking change, but removing a deprecated field (possibly after a certain date) is not bad.

I'm not sure this is related to #215.  

I may be able to take a stab at this if it's considered a valuable thing.

**Comment by kamilkisiela** [comment]
Hi, sounds good! Feel free to work on it, I could help if you want to :)

**Comment by kamilkisiela** [comment]
#506 enables that. Every removal of a deprecated field is *Breaking* by default but you can add a rule to make *Dangerous* so you still get a warning but it won't fail the process.

`--rule suppressRemovalOfDeprecatedField`

**Comment by riffraff** [comment]
awesome, thanks!
