### ISSUE TITLE
Set Access-Control-Allow-Origin on the server, or allow setting it via CLI

### ISSUE THREAD

**Issue by brainlessdeveloper** [kamilkisiela/graphql-inspector#300]
Hello there and thanks for the awesome tool!

I was trying to use `graphql-inspector serve` on my local application as a way of doing a layman's chaos testing session. To get it to work I had to go into the bundled code and change:

```javascript
headers: options.headers,
```

to this:

```javascript
headers: { ...options.headers, 'Access-Control-Allow-Origin': '*' },
```

The variable being called `options` makes me thing it's configurable via the programmatic `@graphql-inspector/core`, but I think it should be possible to set it via CLI too.

What do you think?

**Comment by kamilkisiela** [comment]
You can use `--header`, an example:

```bash
graphql-inspector serve http://localhost:3000 --header 'Access-Control-Allow-Origin: *'
```

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-inspector/pull/354
