### ISSUE TITLE
'Action Required' message from Github App?

### ISSUE THREAD

**Issue by dchambers** [kamilkisiela/graphql-inspector#306]
<img width="1006" alt="Screen Shot 2019-05-24 at 17 20 41" src="https://user-images.githubusercontent.com/283294/58342483-617f7980-7e48-11e9-92bd-8ff959aedac3.png">

Any ideas as to how I can debug things if the Github App simply says 'Action Required', and where clicking the Resolve' link merely opens `https://graphql-inspector.com/` in a new tab?

Thanks for any pointers in advance 😄

**Comment by kamilkisiela** [comment]
Hmm, you should see annotations in **Files changed** tab if not, let us know here

**Comment by dchambers** [comment]
Hi @kamilkisiela, many thanks for the reply 👍. I don't see any annotations in the 'Files changed' tab, or any of the other tabs apart from the 'Checks' tab, where I see this:

<img width="1439" alt="Screen Shot 2019-05-28 at 11 41 17" src="https://user-images.githubusercontent.com/283294/58472233-bc152000-813d-11e9-8bf7-34c6adeef0de.png">

**Comment by kamilkisiela** [comment]
@dchambers it might happen because of missing config or schema file. Could you tell me how your config looks like and where it's located?

Github API changed recently so if you have something like below, please use branch's name directly:

```yaml
schema:
  ref: head/master # <--- head/ prefix
  path: schema.graphql
```

**Comment by dchambers** [comment]
@kamilkisiela, I've been able to make some progress by moving the config to within `package.json`, and it now permanently says 'In progress' rather than the 'Action required' error I had before.

My config within `package.json` is as follows:

```
 ...
  "graphql-inspector": {
    "diff": true,
    "schema": {
      "ref": "master",
      "path": "graphql-middleware/schema.graphql"
    }
  },
  ...
```

where `graphql-middleware/schema.graphql` contains an automatically generated schema (not generated by graphql-inspector though) that's committed to the repo each time any of the schema source files change.

I'm able to manually verify that graphql-inspector is happy with the generated schema file by running this command:

```
graphql-inspector diff graphql-middleware/schema-old.graphql graphql-middleware/schema.graphql
```

and I see very helpful warnings for all the backwardly incompatible changes I've made.

**Comment by dchambers** [comment]
This started working on new branches that were created, so I think there was some issue with getting it to re-run on my force pushed branch that made me think that my changes still weren't working. Thanks so much for the help @kamilkisiela, and for the awesome tool 🙌.

**Comment by lajtmaN** [comment]
We have more or less the same problem in our setup. We installed the Github App, added configuration to `package.json`, but it remains in progress forever. 
We do not have one big schema with everything, we have lots of pieces, which are then imported to the different files. The diff tool in the CLI handles this perfectly which is why I would assume the App would do the same. 
We have the configuration pushed to master (which is the branch we are comparing with), but new PR is still not working. 
Any ideas on how to debug this would be appreciated 👏

**Comment by kamilkisiela** [comment]
@lajtmaN could you share your config?

**Comment by lajtmaN** [comment]
In `package.json`:
```
"graphql-inspector": {
    "diff": true,
    "schema": {
      "ref": "head/master",
      "path": "src/schema/root/schema.graphql"
    }
  }
```
I also tried using just `master`, but with the same results. 

The schema file which we link to contains:
```
# import Query from 'query.graphql'
# import Mutation from 'mutation.graphql'

schema {
  query: Query
  mutation: Mutation
}
```
But as I said earlier, it works fine in the command line.

**Comment by kamilkisiela** [comment]
@lajtmaN could you remove `head/` from `schema.ref`? Github API somehow doesn't handle `head/` prefixes.

One extra thing, Github App won't be able to resolve those imports in your graphql file. It doesn't clone the repository and installs dependencies and then runs GraphQL Inspector CLI but fetches files from Github repository using Github API.

What we usually do is we save an entire schema to one .graphql file and then use it as a reference. You get `git blame` with this plus Github Inspector app works with it. [Here's how we do it](https://graphql-inspector.com/docs/recipes/github).

If you want to use graphql imports and not generate a new file on every commit then [you can also use CLI](https://graphql-inspector.com/docs/recipes/ci).
