### ISSUE TITLE
Add option to disable findDuplicatedFragments test

### ISSUE THREAD

**Issue by saerdnaer** [kamilkisiela/graphql-inspector#311]
In our use case, it would be nice to be able to disable the findDuplicatedFragments test. Is it possible to an option for that?

https://github.com/kamilkisiela/graphql-inspector/blob/7a6d3c8a07aaec50a705477a66cca961f27dec47/packages/core/src/validate/index.ts#L81-L99

**Comment by kamilkisiela** [comment]
#321 should enable that

**Comment by kamilkisiela** [comment]
Released as `1.20.0`

**Comment by MM3y3r** [comment]
Cool! Thank you!
