### ISSUE TITLE
Question: Should glob work with introspection command?

### ISSUE THREAD

**Issue by loremaps** [kamilkisiela/graphql-inspector#349]
We have a modularized server with several `.graphql` files. If I understand correctly from the discussion in #250 it should be possible to do the following workaround (with glob):
```
graphql-inspector introspect path/to/files/**/*.graphql --write schema.graphql
```
In order to get one big schema file.

This makes sense to me, since the `graphql-toolkit` is used to load the schema:
https://github.com/kamilkisiela/graphql-inspector/blob/e87c322703f305323cff947a156a5709877978c7/packages/load/src/schema/index.ts#L2

However the workaround does not work; and it is weird because if I use the `graphql-toolkit` directly, I get the "merge" schema. Please check the codesandbox here:

[![Edit graphql-inspector-glob-introspect](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/graphql-inspector-glob-introspect-ei5jv?fontsize=14)

The `graphql-inspector` seems to get only the first file and not the "merged" schema from the `graphql-tookit`. Can you please clarify if it should be possible to use glob pattern with the `introspect` command of the cli?

Thanks!

**Comment by loremaps** [comment]
I think I just figured this out it should be passed with quotes right? :man_facepalming: 
```
graphql-inspector introspect 'path/to/files/**/*.graphql' --write schema.graphql
```

**Comment by kamilkisiela** [comment]
@loremaps Yeah, I noticed that recently too, either yarn or the terminal itself looks for files at that glob and turns it into a list of matches. Weird :)

**Comment by madiodio** [comment]
Hi @kamilkisiela, this should be highlighted in docs imo, would you welcome a PR for it ? I just wasted a big hour looking for why it was failing.

**Comment by kamilkisiela** [comment]
It's something not Inspector specific but feel free to PR it
