### ISSUE TITLE
How to use API -  a sample node project needed  

### ISSUE THREAD

**Issue by amaranthHe** [kamilkisiela/graphql-inspector#357]
Could you please provide an executable sample node project that demo how to use the API?

**Comment by kamilkisiela** [comment]
If you mean the `@graphql-inspector/api` than it's still in development and with the `@graphql-inspector/ui` creates a base for future desktop application. I just pushed it so anyone from the community could pick it up and continue working on it.

If you meant the CLI, then `/examples` has what you want to see.
