### ISSUE TITLE
graphql-tag-pluck peer dependency

### ISSUE THREAD

**Issue by loremaps** [kamilkisiela/graphql-inspector#452]
Hi,

It seems that `graphql-tag-pluck` is now a peer-dependency of `graphql-toolkit` since `v0.3.2`:
ardatan/graphql-toolkit#152 

Should we add `graphql-tag-pluck` as a dependency (or peer) of `@graphql-inspector/load` package? Or I am missing something else?

With `v1.22.0` I am getting the following error using a command like `graphql-inspector validate 'src/app/**/*.ts' ./schema.graphql`:

```
error Error: Cannot find module 'graphql-tag-pluck'
Require stack:
- /builds/covis-greece/aifind/node_modules/graphql-toolkit/dist/commonjs/utils/extract-document-string-from-code-file.js
- /builds/covis-greece/aifind/node_modules/graphql-toolkit/dist/commonjs/utils/index.js
- /builds/covis-greece/aifind/node_modules/graphql-toolkit/dist/commonjs/epoxy/merge-schemas.js
- /builds/covis-greece/aifind/node_modules/graphql-toolkit/dist/commonjs/epoxy/index.js
- /builds/covis-greece/aifind/node_modules/graphql-toolkit/dist/commonjs/index.js
- /builds/covis-greece/aifind/node_modules/@graphql-inspector/load/dist/documents.js
- /builds/covis-greece/aifind/node_modules/@graphql-inspector/load/dist/index.js
- /builds/covis-greece/aifind/node_modules/@graphql-inspector/cli/dist/commands/diff.js
- /builds/covis-greece/aifind/node_modules/@graphql-inspector/cli/dist/index.js at ./jobtopus-ui/src/app/app.component.spec.ts
```

**Comment by kamilkisiela** [comment]
Yes but I didn't notice that change in `graphql-toolkit`. Hmm I will talk with the team why we move it into peerDeps.

**Comment by kamilkisiela** [comment]
#577

**Comment by kamilkisiela** [comment]
[v1.24.0](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.24.0)

**Comment by loremaps** [comment]
@kamilkisiela sorry for taking so much to test this :disappointed: 

After this fix I am getting the following error, when I try to validate `.ts` docs:
```
error GraphQL template literals cannot be plucked from a TypeScript code without having the "typescript" package installed.
Please install it and try again.
```
According to this DAB0mB/graphql-tag-pluck#11 `typescript` is to be dynamically loaded when needed. Indeed if I install typescript everything works fine.

Do you think it should be a peer-dependency here or upstream on `ardatan/graphql-toolkit` or `DAB0mB/graphql-tag-pluck`? Or maybe a note on the documentation is enough?

Thanks!
