### ISSUE TITLE
GitHub Application does not run checks

### ISSUE THREAD

**Issue by AwolDes** [kamilkisiela/graphql-inspector#457]
I installed the Github Application for my repo with the following in my `package.json`:

```json
{
  "graphql-inspector": {
    "diff": true,
    "schema": {
      "ref": "master",
      "path": "aap/graphql/schema.graphql"
    }
  }
}
```
I also attempted a similar configuration in the `graphql-inspector.yaml` file, but that did not work either.

When I go to check on the checks for a PR, the only thing that has been said is that the job has been queued
![image](https://user-images.githubusercontent.com/9693812/61837556-a4051700-aec8-11e9-9700-42b1f0490d9b.png)

Is this a problem in my configuration, or with the GitHub application? Thanks!

**Comment by ghiculescu** [comment]
This is still an issue, did you mean to close if Austin?

**Comment by kamilkisiela** [comment]
@ghiculescu @AwolDes That's because we reached the paid plan on Netlify, there's over 1 mln requests each month. I recommend to either use GitHub Actions or have your own GitHub Application. In near future, I might turn on some donations to make it sustainable.

**Comment by AwolDes** [comment]
@kamilkisiela thanks for the the clarification.
