### ISSUE TITLE
Diff fails in case of empty GraphQL Types

### ISSUE THREAD

**Issue by woelfle** [kamilkisiela/graphql-inspector#541]
Comparing GraphQL schemas via 
`graphql-inspector diff old-version.graphql new-version.graphql `  

results in a message

`error Unable to find any GraphQL type defintions for the following pointers: new-version.graphql`

in case the file 'new-version.graphql' contains an empty type definition.

I.e. in case 'old-version.graphql' contains the content

```
type PERSON {
  name: String
}
```

and 'new-version.graphql' contains content:

```
type PERSON {
  name: String
}

type ADRESS {
}
```

I guess the expected output would be a message that type 'ADRESS' has been added but that no breaking changes have been detected.

**Comment by kamilkisiela** [comment]
Is empty type a thing in GraphQL? I thought it's invalid... That's why we don't even consider empty types.

**Comment by woelfle** [comment]
> Is empty type a thing in GraphQL? I thought it's invalid... That's why we don't even consider empty types.
I haven't found anything in the GraphQL spec that mentions whether empty types are valid nor not. Therefore it might be subject to interpretation. I've been running into this issue because we are generating the GraphQL schema from Meta-Information in our System. In our case it can happen during development that a new type does not yet have and 'published' features. In that case currently an empty GraphQL type is being created. 

Of course we can work around this issue by omitting the empty GraphQL type and all references to it when creating the GraphQL Schema but I thought that perhaps others might run into this issue too so I decided to let you know about it.

If it is easy to fix this issue as suggested in my issue description we would be happy. If not then that's ok too. In that case we will modify our schema generation algorithm and skip the empt types.

PS: Nice component that you have developed. It is helping us a lot to detect API changes in our schema. Thanks a lot.

**Comment by kamilkisiela** [comment]
@woelfle https://stackblitz.com/edit/graphql-empty-object-type?file=index.ts

Usually what we do is we add `_: String` field and later on we use `extend type`. But that's a workaround.

**Comment by woelfle** [comment]
We have already implemented the workaround that I've described in the last comment. It works well for use. Therefore you can close this ticket if you like.
