### ISSUE TITLE
How to use GraphQL endpoint with Github Actions?

### ISSUE THREAD

**Issue by georgeboot** [kamilkisiela/graphql-inspector#549]
I am trying to configure a github action, but I'm not winning.

Previously, we ran the cli version of this package in CLI like so:
```sh
# write new schema to .gql file
php artisan lighthouse:print > schema.gql

yarn install

# compare with live version
npx graphql-inspector diff https://api.company.com/graphql schema.gql
```

That worked fine.

What I'm now trying, using Actions, is the following:

```yml
# .github/workflows/main.yml

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Check GraphQL with Inspector
      uses: kamilkisiela/graphql-inspector@v1.23.1
```

My config file:
```yml
# .github/graphql-inspector.yaml

diff: true
schema:
  ref: master
  path: https://api.company.com/graphql
```

However, this fails every time I try, with the following output:
```
Run kamilkisiela/graphql-inspector@v1.23.1
/usr/bin/docker run --name fe0f0c71fe765c444dc8bf12b9e05e2cd14c_d74472 --label 29fe0f --workdir /github/workspace --rm -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/repo/repo":"/github/workspace" 29fe0f:0c71fe765c444dc8bf12b9e05e2cd14c
ℹ  info      GraphQL Inspector started
ℹ  info      Failed to find .github/graphql-inspector.yaml file
ℹ  info      Failed to find .github/graphql-inspector.yml file
✖  fatal     No config file
✖  fatal     Failed to find any config file
##[error]Docker run failed with exit code 1
```

What am I doing wrong?

**Comment by kamilkisiela** [comment]
It doesn't support graphql endpoints, only files. I will try to implement it today.

**Comment by kamilkisiela** [comment]
Why do you want to compare it against a deployed GraphQL endpoint and not the master branch?

**Comment by georgeboot** [comment]
Well, technically I could also checkout master branch in a PR and generate the `.graphql` file from there. It's just easier to grab it from the live version as that is for sure whats out there currently. Master technically doesn't have to be deployed.

Note that the error message I'm getting states that the config file could not be found. Or this error message is very misleading, or (more likely) there is more that needs to be fixed than implementing endpoint comparisons.

**Comment by georgeboot** [comment]
@kamilkisiela any clue why it says it can't find my config file?

**Comment by kamilkisiela** [comment]
it will be possible with in next version
#1425

**Comment by kamilkisiela** [comment]
[`v2.0.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v2.0.0) released. Read more about [new GraphQL Inspector](https://the-guild.dev/blog/new-graphql-inspector)

**Comment by kadirselcuk** [comment]
Is the GraphQL inspector endpoint github actions made call here
