### ISSUE TITLE
Publish the CLI as a container to Docker Hub

### ISSUE THREAD

**Issue by spawnia** [kamilkisiela/graphql-inspector#552]
Thanks for the great project.

I saw you created https://github.com/kamilkisiela/graphql-inspector/blob/master/Dockerfile-cli and have also set up a repository at https://hub.docker.com/r/kamilkisiela/graphql-inspector

Can you publish the CLI image there? It is quite simple to set up an automated build with Docker Hub.

**Comment by kamilkisiela** [comment]
#578 should fix it

**Comment by kamilkisiela** [comment]
[v1.24.0](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.24.0)

**Comment by kamilkisiela** [comment]
@spawnia let me know if it works

**Comment by ka765** [comment]
Hello jr
