### ISSUE TITLE
Unable to build schema from a `.graphqls` file

### ISSUE THREAD

**Issue by melo0187** [kamilkisiela/graphql-inspector#560]
I just wanted to give the inspector a try with our existing GraphQL server. We are using the schema first approach with graphql-java-tools and eveyrthing is working.

However, trying to use graphql-inspector's diff command is giving me an error.
```
~/Code/repoRoot/app $: graphql-inspector diff 'git:origin/master:./server/src/main/resources/app.graphqls' './server/src/main/resources/meisterplan.graphqls'
```

The output just says `error Unable to build schema from git` and I don't know where to go from here. The command does not offer any more advice.

Does anyone know in which direction I have to look?

**Comment by kamilkisiela** [comment]
I see... it's because only `.gql` and `.graphql` are accepted. I will fix it soon.

**Comment by kamilkisiela** [comment]
[v1.24.0](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.24.0)

**Comment by melo0187** [comment]
@kamilkisiela thank you for reacting so quickly!

Sadly I'm still out of luck:
```
~/Code/repoRoot/app $: npm install --save-global @graphql-inspector/cli
[...]
+ @graphql-inspector/cli@1.24.0
[...]
~/Code/repoRoot/app $: graphql-inspector diff 'git:origin/master:./server/src/main/resources/app.graphqls' './server/src/main/resources/meisterplan.graphqls'

error Unable to build schema from git
```
