### ISSUE TITLE
command not found: graphql-inspector

### ISSUE THREAD

**Issue by jayqui-omada** [kamilkisiela/graphql-inspector#566]
```bash
npm install --save-global @graphql-inspector/cli
```

installation happens, and `"@graphql-inspector/cli": "^1.23.1",` gets added to the `dependencies` in my package.json

```bash
graphql-inspector --help

zsh: command not found: graphql-inspector
```

Any ideas why this might occur?

**Comment by georgeboot** [comment]
You probably don't have your `node_modules/bin` in your `PATH`.

You could try `npx graphql-inspector --help`

**Comment by kamilkisiela** [comment]
I don't recommend to have it installed globally. The `graphql` package is veeeery sensitive about having multiple different versions of it within a project. But if you still want to have it installed globally, remember to install `graphql` too.

**Comment by bearbytes** [comment]
The reason for this error is that this command does not actually install the program globally, instead, it installs it in a node_modules folder of the current working directory:
`npm install --save-global @graphql-inspector/cli`

Instead, use this command:
`npm install --global @graphql-inspector/cli`

**Comment by kamilkisiela** [comment]
#600
