### ISSUE TITLE
readme update, on cli parts sometimes no documents passed to cli

### ISSUE THREAD

**Issue by maapteh** [kamilkisiela/graphql-inspector#602]
Kamil, awesome library as usual :)

In the main docs sometimes its forgotten to have DOCUMENTS in the cli examples.

Like: `graphql-inspector coverage ./src/schema.ts --require ts-node/register`

but no documents are passed. So it has to be changed into:

`graphql-inspector validate ./src/_generated-hooks.tsx ./src/_generated-schema.graphql --require ts-node/register`

If needed i can update your readme accordingly?

**Comment by kamilkisiela** [comment]
Oh, I missed that somehow. Sure, would be nice to see a Pull Request, could you? :)
