### ISSUE TITLE
github app has broken links

### ISSUE THREAD

**Issue by maapteh** [kamilkisiela/graphql-inspector#611]
https://graphql-inspector.netlify.com 

https://camo.githubusercontent.com/5564131118adde51540f8f851777765e43a5a73c/68747470733a2f2f6772617068716c2d696e73706563746f722e6e65746c6966792e636f6d2f696d672f636c692f6769746875622e6a7067

**Comment by kamilkisiela** [comment]
Are you sure? I changed it a month ago and it seems like it's working, I see it in logs.

**Comment by maapteh** [comment]
try to click the first link :)

**Comment by kamilkisiela** [comment]
I moved from netlify to zeit :) GitHub App points to a lambda function on zeit now.
https://graphql-inspector.now.sh/
