### ISSUE TITLE
Disable output of description changes for schema comparison

### ISSUE THREAD

**Issue by fabsrc** [kamilkisiela/graphql-inspector#616]
It would be great if there was an option/rule to disable the output of description changes when using the `diff` command. We are comparing our deployed GraphQL server's schema against the local schema files, but some descriptions are added during the runtime. So the diff output always includes description changes even though they are actually not changes at all.

Something like this would be really nice to have:

```
graphql-inspector diff $GRAPHQL_ENDPOINT './src/schema/**/*.graphql' --rule ignoreDescriptionChanges
```

**Comment by kamilkisiela** [comment]
#687
