### ISSUE TITLE
Allow custom rules from file

### ISSUE THREAD

**Issue by chunksnbits** [kamilkisiela/graphql-inspector#650]
It would be useful for the CLI to accept custom rules (provided from local filesystem). 

Usage scenario:
In our our schema definition process we differentiate between draft and main schema.

The draft-schema in many parts will differ from the main schema, as it used for schema discussion and testing of future features. 
For the validation and maintenance however we need to ensure that the main schema is a true subset of the draft schema.

For now I have a temporary solution using graphql-inspector/core directly.
But U think this could be generally useful for the CLI to allow the `--rule` paramater to accept local files as well, i.e.: 

```
graphql-inspector .... --rule=./path/to/rules.js
```
If this is ok with you I can chip in with a PR.

**Comment by kamilkisiela** [comment]
Hi :) Yep, it seems reasonable. I can help you with the PR!

**Comment by chunksnbits** [comment]
Pull request is now open. 
I am looking forward to your feedback :)
