### ISSUE TITLE
[Diff] Cannot compare remote schema

### ISSUE THREAD

**Issue by swcarlosrj** [kamilkisiela/graphql-inspector#73]
Repo:
https://github.com/spacexland/api/tree/graphql-inspector

Run:
```bash
graphql-inspector diff https://api.spacex.land/graphql schema.graphql
```
Output:
```bash
✖ Cannot read property '__schema' of undefined
```

**Comment by kamilkisiela** [comment]
Hmm, this is one is a bit bigger to fix, we compare values and introspection result (of graphql endpoint) returns `null` and `undefined` so yeah, I'll fix that later today or tomorrow.

**Comment by swcarlosrj** [comment]
Np, I'll give a look tmw too. Thanks anyways 🤗

**Comment by kamilkisiela** [comment]
`0.13.0-alpha.0`

**Comment by swcarlosrj** [comment]
💯, working!

**Comment by kamilkisiela** [comment]
`0.13.0` :)
