### ISSUE TITLE
[Introspection] It doesn't generate/overwrite the schema.graphql specified file

### ISSUE THREAD

**Issue by swcarlosrj** [kamilkisiela/graphql-inspector#74]
Repo:
https://github.com/spacexland/api/tree/graphql-inspector

Run:
```bash
graphql-inspector introspect src/schema/index.ts --write newschema.graphql --require ts-node/register/transpile-only
```
AFAIK, it should generate a new file called `newschema.graphql`, also, having same name it doesn't overwrite it

Output:
No output (prob it's not even running) as well no`newschema.graphql` file

**Comment by kamilkisiela** [comment]
@swcarlosrj `v0.12.0` should fix that

**Comment by swcarlosrj** [comment]
@kamilkisiela working!
