### ISSUE TITLE
coverage fails with introspection query

### ISSUE THREAD

**Issue by fabsrc** [kamilkisiela/graphql-inspector#754]
Using the `coverage` function with the introspection query (obtained with `getIntrospectionQuery`) results in an Error: 

```
TypeError: Cannot read property 'locations' of undefined
```

I'm aware that `coverage` does not make sense with the introspection query, however I still think this should work. I'm currently trying to create some automated coverage report using queries from a query registry. This query registry also includes introspection queries.

**Comment by ka765** [comment]
Jr. I need you
