### ISSUE TITLE
Definitions in introspected schema are being pretty printed

### ISSUE THREAD

**Issue by mikejewell** [kamilkisiela/graphql-inspector#90]
Hi!

I'm comparing two schemas: one loaded from disk, one introspected from our endpoint. Even if they're both using identical schemas, I'm seeing differences due to newlines being added in type definition comments.

It turns out that the issue is with this process: https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/load/src/schema/index.ts#L18 - the printSchema function is (I think) doing some pretty printing on long comments, which means that they can't be compared to the original.

I'm not sure what the best route to fix it would be, except maybe amending the graphql printSchema function to make pretty printing optional?

Cheers,
Mike

**Comment by kamilkisiela** [comment]
Hi @mikejewell, could you provide an example so I have something to work on?

**Comment by mikejewell** [comment]
Sadly our endpoint is authenticated, but you should be able to test it with something like this:

```
""" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis volutpat lobortis erat, ac elementum magna sagittis id. Pellentesque a mattis arcu, in convallis sapien. Suspendisse a vehicula ante. Cras vel fringilla quam. Mauris feugiat diam quis nibh porta condimentum. Maecenas nisl sem turpis duis. """
type SomeType {
 "some property"
  id: ID!
}
```

If you read that from a local file, you should get the type description as one long line. If you read it from an endpoint, it'll come back as multiple lines due to the pretty printing (as it's longer than 120 characters, I believe). Let me know if I can provide any more info!

**Comment by kamilkisiela** [comment]
#94 might fix it but I still need to create a test case for it
