### ISSUE TITLE
graphql-toolkit's loadSchema require non-null value (options)

### ISSUE THREAD

**Issue by mikejewell** [kamilkisiela/graphql-inspector#91]
The following line is currently passing null into loadSchema, but graphql-toolkit's URL handler expects to be able to look in there for a 'headers' property (see https://github.com/ardatan/graphql-toolkit/blob/master/src/loaders/schema/introspection-from-url.ts#L18):

https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/load/src/schema/index.ts#L32 

This results in the following error:
`error Cannot read property 'headers' of null`

**Comment by kamilkisiela** [comment]
#92 released as `v0.13.3`
