### ISSUE TITLE
unable to use fragments located in a different file

### ISSUE THREAD

**Issue by X4V1** [kamilkisiela/graphql-inspector#941]
I have this:

/graphql/documents/queries/my-query.graphql:
```
query fetchRequestById(
  $requestId: RequestIdentifierInputType!
  $customerLanguage: CustomerLanguage!
) {
  request(requestIdentifier: $requestId, customerLanguage: $customerLanguage) {  
    ...requestFields  
  }
}
```

/graphql/documents/fragments/my-fragment.graphql:
```
fragment requestFields on RequestType {
  identifier {
    id
  }
}

```

The query is tested and is fully working.
The problem is that the query validations failed because the fragment in located in a different file.
The same query with the fragment contained in the same file is validated successfully (so the problem is really the link between the fragment and the query)

the validate command from cli (`graphql-inspector validate ./graphql/documents/**/*.graphql http://localhost:4600/graphiql/`) is giving the following error:
 ```
> graphql-inspector validate ./graphql/documents/**/* http://localhost:4600/graphiql/

error Unable to find any GraphQL type definitions for the following pointers: ./graphql/documents/queries/my-query.graphql
```

I don't know if I missed something but it sound weird to me. Googled it and did not find anything relevant. Please tell me if I'm wrong.

**Comment by kamilkisiela** [comment]
Could you try this?

```diff
- graphql-inspector validate ./graphql/documents/**/* http://localhost:4600/graphiql/
+ graphql-inspector validate './graphql/documents/**/*' http://localhost:4600/graphiql/ 
```

**Comment by X4V1** [comment]
It's working fine. Thank you very much :)
