### ISSUE TITLE
Empty type throws error

### ISSUE THREAD

**Issue by g-gaston** [kamilkisiela/graphql-inspector#97]
Whenever the schema has an empty type, like
```
type Car {

}
```
The inspector throws:

`error Must provide Source. Received: {}`

Is this the expected behavior?

**Comment by kamilkisiela** [comment]
I think so, an empty object type is not something valid in GraphQL, `graphql-js` [can't parse it](https://astexplorer.net/#/gist/e56eabddd90f8aa297bc98a092c5d919/b5d83ff93ff95b474dc6cd03c51ea0d065b6ba36).

**Comment by kamilkisiela** [comment]
I guess we could throw a better error here

**Comment by kamilkisiela** [comment]
https://github.com/ardatan/graphql-toolkit/pull/176 should fix it

**Comment by kamilkisiela** [comment]
Since the PR was merged I need to bump the dependency of `graphql-toolkit` and we're good to go, should be released today :)

**Comment by kamilkisiela** [comment]
I released `v1.22.1`, it includes the fix.
