### ISSUE TITLE
Allow configuration through yaml file

### ISSUE THREAD

**Issue by steebchen** [kamilkisiela/graphql-inspector#98]
I use Go for my GraphQL server and would like to make use of graphql-inspector, but I don't have a package.json there.

It would be great if options could be specified with a yaml file in the .github folder (`.github/graphql-inspector.yml`), which now seems more and more the go-to approach, especially with github actions.

**Comment by kamilkisiela** [comment]
#105 should enable that

**Comment by kamilkisiela** [comment]
Release in [`v1.15.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.15.0)
